//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBillStateService")]
    public interface IBillStateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillStateService/VerifyBillPaymentWithAddData", ReplyAction="http://tempuri.org/IBillStateService/VerifyBillPaymentWithAddDataResponse")]
        string VerifyBillPaymentWithAddData(string Bill_Id, string Payment_Id, string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillStateService/VerifyBillPaymentGetByTermIdAndDateTime", ReplyAction="http://tempuri.org/IBillStateService/VerifyBillPaymentGetByTermIdAndDateTimeRespo" +
            "nse")]
        string VerifyBillPaymentGetByTermIdAndDateTime(System.DateTime FromDate, System.DateTime ToDate, string Username, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillStateServiceChannel : Avarez.ServiceReference1.IBillStateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillStateServiceClient : System.ServiceModel.ClientBase<Avarez.ServiceReference1.IBillStateService>, Avarez.ServiceReference1.IBillStateService {
        
        public BillStateServiceClient() {
        }
        
        public BillStateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillStateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillStateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillStateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VerifyBillPaymentWithAddData(string Bill_Id, string Payment_Id, string Username, string Password) {
            return base.Channel.VerifyBillPaymentWithAddData(Bill_Id, Payment_Id, Username, Password);
        }
        
        public string VerifyBillPaymentGetByTermIdAndDateTime(System.DateTime FromDate, System.DateTime ToDate, string Username, string Password) {
            return base.Channel.VerifyBillPaymentGetByTermIdAndDateTime(FromDate, ToDate, Username, Password);
        }
    }
}
