//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_GetAllShenaseGhabzInfo
    {
        public long fldid { get; set; }
        public string fldInformaticesCode { get; set; }
        public Nullable<byte> fldServiceCode { get; set; }
        public Nullable<byte> start { get; set; }
        public int type { get; set; }
    }
}
