//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_GetCountryDivForWebService
    {
        public Nullable<int> fldID { get; set; }
        public string fldNodeName { get; set; }
        public Nullable<byte> fldNodeType { get; set; }
        public Nullable<int> fldPID { get; set; }
        public string fldPath { get; set; }
    }
}
