//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_OnlinePayments_LogSelect
    {
        public long fldID { get; set; }
        public string بانک { get; set; }
        public long کد_فیش { get; set; }
        public string کد_موقت { get; set; }
        public Nullable<bool> پرداخت_نهایی { get; set; }
        public string کد_رهگیری { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string کاربر_ایجاد_کننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
