//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_PcPosTransactionSelect
    {
        public int fldId { get; set; }
        public long fldCarFileId { get; set; }
        public int fldPrice { get; set; }
        public bool fldStatus { get; set; }
        public string fldTrackingCode { get; set; }
        public long fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldStatusName { get; set; }
        public string fldShGhabz { get; set; }
        public string fldShPardakht { get; set; }
    }
}
