//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_SubSetting_LogSelect
    {
        public int fldID { get; set; }
        public byte کد_شروع_شناسه_قبض { get; set; }
        public Nullable<byte> نحوه_گرد_کردن { get; set; }
        public string چاپ_شناسه_قبض { get; set; }
        public string معافیت_خودروهای_صفر { get; set; }
        public string عنوان_کاربرد_در_گزارش { get; set; }
        public int آخرین_مهلت_پرداخت { get; set; }
        public string موقعیت_تنظیمات { get; set; }
        public string تاریخ_اعمال { get; set; }
        public string اعمال_برای_زیر_شاخه_تقسیمات_کشوری_ { get; set; }
        public string موقعیت_وسیله_نقلیه { get; set; }
        public string اعمال_برای_زیر_شاخه_سری_خودرو_ { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string کاربر_ایجاد_کننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
