//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_tblGuestInfoSelect
    {
        public int fldId { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldCodeMeli { get; set; }
        public string fldMobile { get; set; }
        public int fldMunId { get; set; }
        public string fldUserName { get; set; }
        public string fldPasssword { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldCountryDivTempId { get; set; }
    }
}
