//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_User_LogSelect
    {
        public long fldID { get; set; }
        public string نام { get; set; }
        public string نام_خانوادگی { get; set; }
        public bool وضعیت { get; set; }
        public string کلمه_عبور { get; set; }
        public string نام_کاربری { get; set; }
        public string کد_ملی { get; set; }
        public string پست_الکترونیکی { get; set; }
        public string پیش_شماره_تلفن { get; set; }
        public string تلفن { get; set; }
        public string همراه { get; set; }
        public string شروع_کار { get; set; }
        public string موقعیت_کاربر { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string کاربر_ایجاد_کننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
