//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_YearBudget_TafriqSelect
    {
        public Nullable<int> Id { get; set; }
        public string MonthTitle { get; set; }
        public Nullable<int> Month_No { get; set; }
        public Nullable<float> Percents { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<long> vosoli { get; set; }
        public Nullable<float> adamVosool { get; set; }
    }
}
