//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class spr_peacocary
    {
        public long fldID { get; set; }
        public long fldCarFileID { get; set; }
        public System.DateTime fldIssuanceDate { get; set; }
        public int fldAccountBankID { get; set; }
        public string fldPeacockeryCode { get; set; }
        public int fldMainComplications { get; set; }
        public int fldFine { get; set; }
        public int fldValueAdded { get; set; }
        public int fldOther { get; set; }
        public int fldShowMoney { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public System.DateTime fldFromDate { get; set; }
        public System.DateTime fldToDate { get; set; }
        public Nullable<int> fldDiscountedAmount { get; set; }
        public Nullable<int> fldDiscountedValue { get; set; }
        public Nullable<int> fldDiscountsOther { get; set; }
        public string fldShGhabz { get; set; }
        public string fldShPardakht { get; set; }
        public int fldDiscountsFine { get; set; }
    }
}
