//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    
    public partial class prs_rptSooratHesab_Header
    {
        public string fldsh_Maliyati { get; set; }
        public string fldTarikhSoodor { get; set; }
        public string fldTarikhEijad { get; set; }
        public string fldSerial { get; set; }
        public string fldSh_Marja { get; set; }
        public string fldTypeSooratHesab { get; set; }
        public string fldNamePettern { get; set; }
        public string fldkh_Eghtesadi { get; set; }
        public string fldkh_CodePosti { get; set; }
        public string fldkh_CodeShobe { get; set; }
        public string fldkh_NationalCode { get; set; }
        public string fldf_CodeEghtesadi { get; set; }
        public string fldf_CodePosti { get; set; }
        public string fldf_CodeShobe { get; set; }
        public string fldf_NationalCode { get; set; }
        public string fldSubject { get; set; }
        public string fldFlyType { get; set; }
        public string fldPas_No { get; set; }
        public string fldParvane_No { get; set; }
        public string fldCodeEzhar { get; set; }
        public string fldCotazh_No { get; set; }
        public string fldCotazh_Date { get; set; }
        public string fldEshterak_No { get; set; }
        public string fldSumMablagh { get; set; }
        public string fldSumTakhfif { get; set; }
        public string fldSumMablagh_Takhfif { get; set; }
        public string fldSumMaliyat { get; set; }
        public string fldSumMablaghSayer { get; set; }
        public string fldSumSooratheasb { get; set; }
        public string fldSumVaznKhales { get; set; }
        public string fldArzeshReyali { get; set; }
        public string fldArzeshArzi { get; set; }
        public string fldRaveshTasviye { get; set; }
        public string fldMablaghNaghdi { get; set; }
        public string fldMablaghNesiye { get; set; }
        public string fldSumSahmMaliyat { get; set; }
        public string fldMaliyat17 { get; set; }
        public string fldUniqCode { get; set; }
    }
}
