//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    
    public partial class prs_User_GharardadSelect
    {
        public long fldID { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public bool fldStatus { get; set; }
        public string fldUserName { get; set; }
        public string fldMelliCode { get; set; }
        public string fldStartDate { get; set; }
        public Nullable<long> fldCountryDivisionsID { get; set; }
        public string fldUserName1 { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldPassword { get; set; }
        public byte fldUserType { get; set; }
        public Nullable<int> fldTarfGharardadId { get; set; }
        public string fldStatusName { get; set; }
        public string fldNameTypeShakhs { get; set; }
        public long fldShakhsId { get; set; }
    }
}
