//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class Sp_FilesSelect
    {
        public int fldId { get; set; }
        public byte[] fldImage { get; set; }
        public Nullable<long> fldUserId { get; set; }
        public Nullable<bool> fldIsAccept { get; set; }
        public Nullable<long> fldKarbarTaeed { get; set; }
        public Nullable<System.DateTime> fldDateAccept { get; set; }
        public string fldNameKarbar { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
    }
}
