//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_FriendsSelect
    {
        public int fldID { get; set; }
        public long fldUser { get; set; }
        public string fldUserName { get; set; }
        public long fldFriends { get; set; }
        public string fldFriendsName { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
    }
}
