//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_Offices_LogSelect
    {
        public long fldID { get; set; }
        public string نام_دفتر { get; set; }
        public string آدرس { get; set; }
        public string نوع_دفتر { get; set; }
        public string شهرداری { get; set; }
        public string منطقه { get; set; }
        public string ناحیه { get; set; }
        public string تلفن { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string کاربر_ایجاد_کننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
