//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_PictureSelect
    {
        public int fldID { get; set; }
        public byte[] fldPic { get; set; }
        public string fldMunicipalityPic { get; set; }
        public Nullable<int> fldMunicipalityPicID { get; set; }
        public string fldBankPic { get; set; }
        public Nullable<int> fldBankPicID { get; set; }
        public string fldUserPic { get; set; }
        public Nullable<long> fldUserPicID { get; set; }
        public string fldUserName { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
    }
}
