//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_PcPosParam_DetailSelect
    {
        public int fldId { get; set; }
        public int fldParamId { get; set; }
        public string fldValue { get; set; }
        public long fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameParametr { get; set; }
        public int fldPcPosInfoId { get; set; }
    }
}
