//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_PishkhanPosSelect
    {
        public int fldId { get; set; }
        public Nullable<long> fldFishId { get; set; }
        public Nullable<int> fldPrice { get; set; }
        public Nullable<byte> fldStatus { get; set; }
        public string fldSerial { get; set; }
        public string fldPosString { get; set; }
        public string fldTermId { get; set; }
        public string fldTrace { get; set; }
        public string fldRRN { get; set; }
        public Nullable<long> fldUserId { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public string fldDesc { get; set; }
    }
}
