//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_RegionTree
    {
        public Nullable<int> ID { get; set; }
        public string NodeName { get; set; }
        public Nullable<int> NodeType { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> SourceID { get; set; }
    }
}
