//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_RptMonthlyUser_CountWithDate_NotPay
    {
        public Nullable<int> fldCount { get; set; }
        public Nullable<int> fldUserID { get; set; }
        public string UserName { get; set; }
        public string fldMonth { get; set; }
    }
}
