//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_tblCentralSamanOrdersSelect
    {
        public int fldId { get; set; }
        public Nullable<int> fldMablagh { get; set; }
        public string fldMunName { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public string fldRefNum { get; set; }
    }
}
