//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    
    public partial class prs_tblKala_KhedmatSelect
    {
        public long fldId { get; set; }
        public string fldCode { get; set; }
        public Nullable<byte> fldTypeShenaseId { get; set; }
        public string fldTarikh { get; set; }
        public string fldRunDate { get; set; }
        public string fldExpDate { get; set; }
        public Nullable<bool> fldSpecialOrGeneral { get; set; }
        public Nullable<bool> fldTaxableOrFree { get; set; }
        public Nullable<byte> fldVat { get; set; }
        public Nullable<byte> fldVatCustomPurposes { get; set; }
        public string fldDescriptionOfID { get; set; }
        public string fldNameShenase { get; set; }
        public string fldSpecialOrGeneralName { get; set; }
        public string fldTaxableOrFreeName { get; set; }
    }
}
