//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class prs_newCarFileCalc
    {
        public int fldid { get; set; }
        public Nullable<int> fldCarId { get; set; }
        public Nullable<short> fldYear { get; set; }
        public string fldShStartDate { get; set; }
        public string fldShEndDate { get; set; }
        public Nullable<int> fldPrice { get; set; }
        public Nullable<int> fldClassId { get; set; }
        public Nullable<int> fldMablaghMoaser { get; set; }
        public Nullable<int> fldValueAdded { get; set; }
        public Nullable<int> fldFinalPrice { get; set; }
        public Nullable<short> fldNobatMohasebe { get; set; }
        public string fldCalcDate { get; set; }
        public Nullable<short> fldTedadJarime { get; set; }
        public Nullable<int> fldMablaghJarime { get; set; }
        public Nullable<int> fldNoMashmol { get; set; }
        public Nullable<int> fldMashmol { get; set; }
        public Nullable<bool> fldLateFine { get; set; }
        public Nullable<bool> fldFineType { get; set; }
        public Nullable<bool> fldCalcFromVariz { get; set; }
        public string fldAzAkharinTarikh { get; set; }
        public Nullable<System.DateTime> fldDiscontStartDate { get; set; }
        public Nullable<System.DateTime> fldDiscontEndDate { get; set; }
        public Nullable<bool> fldDiscountComplicationPrice { get; set; }
        public Nullable<bool> fldDiscontFine { get; set; }
        public Nullable<bool> fldDiscontValueAdded { get; set; }
        public Nullable<bool> fldDiscontOther { get; set; }
        public Nullable<int> fldPercentDiscount { get; set; }
        public Nullable<bool> fldEffectiveUser { get; set; }
        public Nullable<bool> fldEffectiveOffice { get; set; }
        public Nullable<bool> fldEffectiveMunicipality { get; set; }
        public Nullable<int> fldRowNobatId { get; set; }
        public Nullable<int> fldCollectionPrice { get; set; }
        public Nullable<int> fldOtherPrice { get; set; }
        public Nullable<int> fldDiscontMoaserPrice { get; set; }
        public Nullable<int> fldDiscontJarimePrice { get; set; }
        public Nullable<int> fldDiscontValueAddPrice { get; set; }
        public Nullable<int> fldDiscontOtherPrice { get; set; }
        public Nullable<short> fldShModel { get; set; }
        public Nullable<bool> fldExemptNewProduction { get; set; }
        public Nullable<int> fldCollectionId { get; set; }
        public Nullable<int> fldDept { get; set; }
        public Nullable<int> fldDiscount { get; set; }
        public string fldOldCalcDate { get; set; }
    }
}
