//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_jCalcCarFile_test1
    {
        public Nullable<System.DateTime> Column1 { get; set; }
        public Nullable<System.DateTime> Column2 { get; set; }
        public Nullable<System.DateTime> Column3 { get; set; }
        public Nullable<System.DateTime> Column4 { get; set; }
    }
}
