//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_jCalcSingleBaze
    {
        public Nullable<int> fldyear { get; set; }
        public Nullable<long> fldFirstPrice { get; set; }
        public Nullable<long> fldCurectPrice { get; set; }
        public Nullable<long> fldValueAdded { get; set; }
        public Nullable<long> fldFinalPrice { get; set; }
        public Nullable<long> fldFine { get; set; }
        public Nullable<long> fldCountMonth { get; set; }
        public Nullable<long> fldDiscount { get; set; }
        public Nullable<long> fldDept { get; set; }
    }
}
