//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_NewsSelect
    {
        public long fldID { get; set; }
        public string fldSubject { get; set; }
        public string fldMemo { get; set; }
        public bool fldShowStatus { get; set; }
        public string fldMunicipalityName { get; set; }
        public Nullable<int> fldMunicipalityID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldShowStatusName { get; set; }
    }
}
