//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_RptCollectionWithDate
    {
        public long fldID { get; set; }
        public long fldCarFileID { get; set; }
        public string fldCollectionDate { get; set; }
        public int fldPrice { get; set; }
        public int fldSettleTypeID { get; set; }
        public Nullable<long> fldPeacockeryCode { get; set; }
        public Nullable<long> fldTrackCode { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTrackCodePishkhan { get; set; }
        public Nullable<int> fldFinalPayment { get; set; }
        public string fldBankName { get; set; }
        public string username { get; set; }
        public Nullable<int> fldMunID { get; set; }
        public string fldPayType { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldName { get; set; }
        public string fldMelli_EconomicCode { get; set; }
        public string fldStart { get; set; }
        public string fldEnd { get; set; }
        public string fldIssuanceDate { get; set; }
        public string fldShGhabz { get; set; }
        public string fldShPardakht { get; set; }
        public string CarPlaque { get; set; }
        public string fldFile { get; set; }
        public Nullable<long> fldPeacockeryId { get; set; }
    }
}
