//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class Sp_RegisterSelect
    {
        public long fldId { get; set; }
        public int fldCodeDaftar { get; set; }
        public string fldAddress { get; set; }
        public string fldTel { get; set; }
        public int fldMunId { get; set; }
        public Nullable<long> fldLocalId { get; set; }
        public Nullable<long> fldAreaId { get; set; }
        public bool fldState { get; set; }
        public string MunName { get; set; }
        public string LocaName { get; set; }
        public string AreaName { get; set; }
        public string fldModirDaftar { get; set; }
        public string fldmodirFamily { get; set; }
        public string fldcodeMeli { get; set; }
        public string fldStateTitle { get; set; }
        public string fldCodeEghtesadi { get; set; }
        public string fldSh_Sabt { get; set; }
        public bool fldTypePerson { get; set; }
        public string fldTypePersonName { get; set; }
        public string fldMobile { get; set; }
        public string fldExpireDate { get; set; }
    }
}
