//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_SelectCarDetilsByCarFileID
    {
        public long fldID { get; set; }
        public Nullable<long> fldCarID { get; set; }
        public string fldDatePlaque { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldVIN { get; set; }
        public string fldColor { get; set; }
        public Nullable<short> fldModel { get; set; }
        public string fldStartDateInsurance { get; set; }
        public Nullable<long> fldOwnerID { get; set; }
        public string fldOwnerName { get; set; }
        public string fldCarClassName { get; set; }
        public string fldCarModel { get; set; }
        public string fldCarSystemName { get; set; }
        public string fldCarCabinName { get; set; }
        public string fldCarAccountName { get; set; }
        public string fldCarMakeName { get; set; }
        public string fldPlaquNumber { get; set; }
        public string fldMelli_EconomicCode { get; set; }
        public Nullable<int> fldCarModelID { get; set; }
        public Nullable<int> fldCarSystemID { get; set; }
        public Nullable<int> fldCarAccountTypeID { get; set; }
        public Nullable<int> fldCabinTypeID { get; set; }
        public Nullable<int> fldCarMakeID { get; set; }
        public Nullable<int> fldCarClassID { get; set; }
        public int fldCarPlaqueID { get; set; }
        public string fldPlaqueCityName { get; set; }
        public string fldPlaqueSerial { get; set; }
        public string fldCarPlaqueNumber { get; set; }
        public string fldFuelType { get; set; }
        public string fldCylinder_Wheel_Pivot { get; set; }
    }
}
