//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_UpAccountBankSelect
    {
        public int fldID { get; set; }
        public string fldAccountNumber { get; set; }
        public int fldBranchID { get; set; }
        public long fldCountryDivisionsID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
    }
}
