//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cartaxtest2Entities : DbContext
    {
        public cartaxtest2Entities()
            : base("name=cartaxtest2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<prs_tblTarfGharardadSelect> prs_tblTarfGharardadSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblTarfGharardadSelect>("prs_tblTarfGharardadSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<prs_User_GharardadSelect> prs_User_GharardadSelect(string fieldname, string value, Nullable<int> h, string pass, Nullable<int> fldUserId, string fldUserPass)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldUserPassParameter = fldUserPass != null ?
                new ObjectParameter("fldUserPass", fldUserPass) :
                new ObjectParameter("fldUserPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_User_GharardadSelect>("prs_User_GharardadSelect", fieldnameParameter, valueParameter, hParameter, passParameter, fldUserIdParameter, fldUserPassParameter);
        }
    
        public virtual int prs_tblShakhsHaghighi_HoghoghiDelete(Nullable<long> fldId, Nullable<long> fldUserId, string fldUserPass, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldUserPassParameter = fldUserPass != null ?
                new ObjectParameter("fldUserPass", fldUserPass) :
                new ObjectParameter("fldUserPass", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblShakhsHaghighi_HoghoghiDelete", fldIdParameter, fldUserIdParameter, fldUserPassParameter, fldIPParameter);
        }
    
        public virtual int prs_tblShakhsHaghighi_HoghoghiInsert(string fldName, string fldFamily, string fldNationalCode, string fldCodeEghtesadi, Nullable<byte> fldTypeShakhsId, string fldCodePosti, string fldCodeShobe, Nullable<long> fldOwnerId, Nullable<long> fldUserID, string fldDesc, string fldIP)
        {
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldFamilyParameter = fldFamily != null ?
                new ObjectParameter("fldFamily", fldFamily) :
                new ObjectParameter("fldFamily", typeof(string));
    
            var fldNationalCodeParameter = fldNationalCode != null ?
                new ObjectParameter("fldNationalCode", fldNationalCode) :
                new ObjectParameter("fldNationalCode", typeof(string));
    
            var fldCodeEghtesadiParameter = fldCodeEghtesadi != null ?
                new ObjectParameter("fldCodeEghtesadi", fldCodeEghtesadi) :
                new ObjectParameter("fldCodeEghtesadi", typeof(string));
    
            var fldTypeShakhsIdParameter = fldTypeShakhsId.HasValue ?
                new ObjectParameter("fldTypeShakhsId", fldTypeShakhsId) :
                new ObjectParameter("fldTypeShakhsId", typeof(byte));
    
            var fldCodePostiParameter = fldCodePosti != null ?
                new ObjectParameter("fldCodePosti", fldCodePosti) :
                new ObjectParameter("fldCodePosti", typeof(string));
    
            var fldCodeShobeParameter = fldCodeShobe != null ?
                new ObjectParameter("fldCodeShobe", fldCodeShobe) :
                new ObjectParameter("fldCodeShobe", typeof(string));
    
            var fldOwnerIdParameter = fldOwnerId.HasValue ?
                new ObjectParameter("fldOwnerId", fldOwnerId) :
                new ObjectParameter("fldOwnerId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblShakhsHaghighi_HoghoghiInsert", fldNameParameter, fldFamilyParameter, fldNationalCodeParameter, fldCodeEghtesadiParameter, fldTypeShakhsIdParameter, fldCodePostiParameter, fldCodeShobeParameter, fldOwnerIdParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_tblShakhsHaghighi_HoghoghiSelect> prs_tblShakhsHaghighi_HoghoghiSelect(string fieldname, string value, Nullable<long> userId, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblShakhsHaghighi_HoghoghiSelect>("prs_tblShakhsHaghighi_HoghoghiSelect", fieldnameParameter, valueParameter, userIdParameter, hParameter);
        }
    
        public virtual int prs_tblShakhsHaghighi_HoghoghiUpdate(Nullable<long> fldId, string fldName, string fldFamily, string fldNationalCode, string fldCodeEghtesadi, Nullable<byte> fldTypeShakhsId, string fldCodePosti, string fldCodeShobe, Nullable<long> fldOwnerId, Nullable<long> fldUserID, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldFamilyParameter = fldFamily != null ?
                new ObjectParameter("fldFamily", fldFamily) :
                new ObjectParameter("fldFamily", typeof(string));
    
            var fldNationalCodeParameter = fldNationalCode != null ?
                new ObjectParameter("fldNationalCode", fldNationalCode) :
                new ObjectParameter("fldNationalCode", typeof(string));
    
            var fldCodeEghtesadiParameter = fldCodeEghtesadi != null ?
                new ObjectParameter("fldCodeEghtesadi", fldCodeEghtesadi) :
                new ObjectParameter("fldCodeEghtesadi", typeof(string));
    
            var fldTypeShakhsIdParameter = fldTypeShakhsId.HasValue ?
                new ObjectParameter("fldTypeShakhsId", fldTypeShakhsId) :
                new ObjectParameter("fldTypeShakhsId", typeof(byte));
    
            var fldCodePostiParameter = fldCodePosti != null ?
                new ObjectParameter("fldCodePosti", fldCodePosti) :
                new ObjectParameter("fldCodePosti", typeof(string));
    
            var fldCodeShobeParameter = fldCodeShobe != null ?
                new ObjectParameter("fldCodeShobe", fldCodeShobe) :
                new ObjectParameter("fldCodeShobe", typeof(string));
    
            var fldOwnerIdParameter = fldOwnerId.HasValue ?
                new ObjectParameter("fldOwnerId", fldOwnerId) :
                new ObjectParameter("fldOwnerId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblShakhsHaghighi_HoghoghiUpdate", fldIdParameter, fldNameParameter, fldFamilyParameter, fldNationalCodeParameter, fldCodeEghtesadiParameter, fldTypeShakhsIdParameter, fldCodePostiParameter, fldCodeShobeParameter, fldOwnerIdParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_tblTarfGharardadDelete(Nullable<int> fldId, Nullable<long> fldUserId, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblTarfGharardadDelete", fldIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual int prs_tblTarfGharardadInsert(ObjectParameter fldId, Nullable<long> fldShakhsId, string fldUniqId, byte[] fldPrivateKey, byte[] fldSignatureCertificate, Nullable<long> fldUserID, string fldDesc, string fldIP)
        {
            var fldShakhsIdParameter = fldShakhsId.HasValue ?
                new ObjectParameter("fldShakhsId", fldShakhsId) :
                new ObjectParameter("fldShakhsId", typeof(long));
    
            var fldUniqIdParameter = fldUniqId != null ?
                new ObjectParameter("fldUniqId", fldUniqId) :
                new ObjectParameter("fldUniqId", typeof(string));
    
            var fldPrivateKeyParameter = fldPrivateKey != null ?
                new ObjectParameter("fldPrivateKey", fldPrivateKey) :
                new ObjectParameter("fldPrivateKey", typeof(byte[]));
    
            var fldSignatureCertificateParameter = fldSignatureCertificate != null ?
                new ObjectParameter("fldSignatureCertificate", fldSignatureCertificate) :
                new ObjectParameter("fldSignatureCertificate", typeof(byte[]));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblTarfGharardadInsert", fldId, fldShakhsIdParameter, fldUniqIdParameter, fldPrivateKeyParameter, fldSignatureCertificateParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_tblTarfGharardadUpdate(Nullable<int> fldId, Nullable<long> fldShakhsId, string fldUniqId, byte[] fldPrivateKey, byte[] fldSignatureCertificate, Nullable<long> fldUserID, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldShakhsIdParameter = fldShakhsId.HasValue ?
                new ObjectParameter("fldShakhsId", fldShakhsId) :
                new ObjectParameter("fldShakhsId", typeof(long));
    
            var fldUniqIdParameter = fldUniqId != null ?
                new ObjectParameter("fldUniqId", fldUniqId) :
                new ObjectParameter("fldUniqId", typeof(string));
    
            var fldPrivateKeyParameter = fldPrivateKey != null ?
                new ObjectParameter("fldPrivateKey", fldPrivateKey) :
                new ObjectParameter("fldPrivateKey", typeof(byte[]));
    
            var fldSignatureCertificateParameter = fldSignatureCertificate != null ?
                new ObjectParameter("fldSignatureCertificate", fldSignatureCertificate) :
                new ObjectParameter("fldSignatureCertificate", typeof(byte[]));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblTarfGharardadUpdate", fldIdParameter, fldShakhsIdParameter, fldUniqIdParameter, fldPrivateKeyParameter, fldSignatureCertificateParameter, fldUserIDParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_tblTypeShakhsSelect> prs_tblTypeShakhsSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblTypeShakhsSelect>("prs_tblTypeShakhsSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_User_GharardadInsert(ObjectParameter fldId, Nullable<int> fldTarfGharardadId, Nullable<bool> fldStatus, string fldPassword, string fldUserName, Nullable<long> fldUserID, string fldDesc, byte[] fldImage)
        {
            var fldTarfGharardadIdParameter = fldTarfGharardadId.HasValue ?
                new ObjectParameter("fldTarfGharardadId", fldTarfGharardadId) :
                new ObjectParameter("fldTarfGharardadId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(bool));
    
            var fldPasswordParameter = fldPassword != null ?
                new ObjectParameter("fldPassword", fldPassword) :
                new ObjectParameter("fldPassword", typeof(string));
    
            var fldUserNameParameter = fldUserName != null ?
                new ObjectParameter("fldUserName", fldUserName) :
                new ObjectParameter("fldUserName", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldImageParameter = fldImage != null ?
                new ObjectParameter("fldImage", fldImage) :
                new ObjectParameter("fldImage", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_User_GharardadInsert", fldId, fldTarfGharardadIdParameter, fldStatusParameter, fldPasswordParameter, fldUserNameParameter, fldUserIDParameter, fldDescParameter, fldImageParameter);
        }
    
        public virtual int prs_User_GharardadUpdate(Nullable<long> fldID, Nullable<int> fldTarfGharardadId, Nullable<bool> fldStatus, string fldUserName, Nullable<long> fldUserID, string fldDesc, byte[] fldpic)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(long));
    
            var fldTarfGharardadIdParameter = fldTarfGharardadId.HasValue ?
                new ObjectParameter("fldTarfGharardadId", fldTarfGharardadId) :
                new ObjectParameter("fldTarfGharardadId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(bool));
    
            var fldUserNameParameter = fldUserName != null ?
                new ObjectParameter("fldUserName", fldUserName) :
                new ObjectParameter("fldUserName", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldpicParameter = fldpic != null ?
                new ObjectParameter("fldpic", fldpic) :
                new ObjectParameter("fldpic", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_User_GharardadUpdate", fldIDParameter, fldTarfGharardadIdParameter, fldStatusParameter, fldUserNameParameter, fldUserIDParameter, fldDescParameter, fldpicParameter);
        }
    
        public virtual ObjectResult<prs_tblMeasureUnitSelect> prs_tblMeasureUnitSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblMeasureUnitSelect>("prs_tblMeasureUnitSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<prs_tblKala_KhedmatSelect> prs_tblKala_KhedmatSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblKala_KhedmatSelect>("prs_tblKala_KhedmatSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<prs_SelectDetailSooratHesab> prs_SelectDetailSooratHesab(Nullable<long> fldIdSooratHesab)
        {
            var fldIdSooratHesabParameter = fldIdSooratHesab.HasValue ?
                new ObjectParameter("fldIdSooratHesab", fldIdSooratHesab) :
                new ObjectParameter("fldIdSooratHesab", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_SelectDetailSooratHesab>("prs_SelectDetailSooratHesab", fldIdSooratHesabParameter);
        }
    
        public virtual ObjectResult<prs_SelectHeaderSooratHesab> prs_SelectHeaderSooratHesab(Nullable<long> fldIdSooratHesab)
        {
            var fldIdSooratHesabParameter = fldIdSooratHesab.HasValue ?
                new ObjectParameter("fldIdSooratHesab", fldIdSooratHesab) :
                new ObjectParameter("fldIdSooratHesab", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_SelectHeaderSooratHesab>("prs_SelectHeaderSooratHesab", fldIdSooratHesabParameter);
        }
    
        public virtual int prs_tblSooratHesabHeader_ValueInsert(Nullable<long> fldHeaderId, string fldValue, Nullable<short> fldParametrHeaderId, Nullable<long> fldUserId, string fldIP)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldParametrHeaderIdParameter = fldParametrHeaderId.HasValue ?
                new ObjectParameter("fldParametrHeaderId", fldParametrHeaderId) :
                new ObjectParameter("fldParametrHeaderId", typeof(short));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabHeader_ValueInsert", fldHeaderIdParameter, fldValueParameter, fldParametrHeaderIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_tblCurrencyTypeSelect> prs_tblCurrencyTypeSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblCurrencyTypeSelect>("prs_tblCurrencyTypeSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_tblSooratHesab_DetailInsert(Nullable<long> fldHeaderId, Nullable<long> fldUserID, string fldIP)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_DetailInsert", fldHeaderIdParameter, fldUserIDParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesab_HeaderInsert(ObjectParameter fldid, string fldTaxId, Nullable<System.DateTime> fldIndatim, Nullable<System.DateTime> fldIndati2m, Nullable<byte> fldInty, Nullable<byte> fldInp, string fldInno, string fldIrtaxId, Nullable<long> fldKharidarId, Nullable<long> fldForooshandeId, string fldFunctionName, string fldkh_Pas_No, Nullable<byte> fldkh_TypeFly, string fldF_Sh_Parvane, string fldF_GomrokCode, string fldF_UniqId, string fldShomareFish, Nullable<long> fldUserId, string fldIP)
        {
            var fldTaxIdParameter = fldTaxId != null ?
                new ObjectParameter("fldTaxId", fldTaxId) :
                new ObjectParameter("fldTaxId", typeof(string));
    
            var fldIndatimParameter = fldIndatim.HasValue ?
                new ObjectParameter("fldIndatim", fldIndatim) :
                new ObjectParameter("fldIndatim", typeof(System.DateTime));
    
            var fldIndati2mParameter = fldIndati2m.HasValue ?
                new ObjectParameter("fldIndati2m", fldIndati2m) :
                new ObjectParameter("fldIndati2m", typeof(System.DateTime));
    
            var fldIntyParameter = fldInty.HasValue ?
                new ObjectParameter("fldInty", fldInty) :
                new ObjectParameter("fldInty", typeof(byte));
    
            var fldInpParameter = fldInp.HasValue ?
                new ObjectParameter("fldInp", fldInp) :
                new ObjectParameter("fldInp", typeof(byte));
    
            var fldInnoParameter = fldInno != null ?
                new ObjectParameter("fldInno", fldInno) :
                new ObjectParameter("fldInno", typeof(string));
    
            var fldIrtaxIdParameter = fldIrtaxId != null ?
                new ObjectParameter("fldIrtaxId", fldIrtaxId) :
                new ObjectParameter("fldIrtaxId", typeof(string));
    
            var fldKharidarIdParameter = fldKharidarId.HasValue ?
                new ObjectParameter("fldKharidarId", fldKharidarId) :
                new ObjectParameter("fldKharidarId", typeof(long));
    
            var fldForooshandeIdParameter = fldForooshandeId.HasValue ?
                new ObjectParameter("fldForooshandeId", fldForooshandeId) :
                new ObjectParameter("fldForooshandeId", typeof(long));
    
            var fldFunctionNameParameter = fldFunctionName != null ?
                new ObjectParameter("fldFunctionName", fldFunctionName) :
                new ObjectParameter("fldFunctionName", typeof(string));
    
            var fldkh_Pas_NoParameter = fldkh_Pas_No != null ?
                new ObjectParameter("fldkh_Pas_No", fldkh_Pas_No) :
                new ObjectParameter("fldkh_Pas_No", typeof(string));
    
            var fldkh_TypeFlyParameter = fldkh_TypeFly.HasValue ?
                new ObjectParameter("fldkh_TypeFly", fldkh_TypeFly) :
                new ObjectParameter("fldkh_TypeFly", typeof(byte));
    
            var fldF_Sh_ParvaneParameter = fldF_Sh_Parvane != null ?
                new ObjectParameter("fldF_Sh_Parvane", fldF_Sh_Parvane) :
                new ObjectParameter("fldF_Sh_Parvane", typeof(string));
    
            var fldF_GomrokCodeParameter = fldF_GomrokCode != null ?
                new ObjectParameter("fldF_GomrokCode", fldF_GomrokCode) :
                new ObjectParameter("fldF_GomrokCode", typeof(string));
    
            var fldF_UniqIdParameter = fldF_UniqId != null ?
                new ObjectParameter("fldF_UniqId", fldF_UniqId) :
                new ObjectParameter("fldF_UniqId", typeof(string));
    
            var fldShomareFishParameter = fldShomareFish != null ?
                new ObjectParameter("fldShomareFish", fldShomareFish) :
                new ObjectParameter("fldShomareFish", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_HeaderInsert", fldid, fldTaxIdParameter, fldIndatimParameter, fldIndati2mParameter, fldIntyParameter, fldInpParameter, fldInnoParameter, fldIrtaxIdParameter, fldKharidarIdParameter, fldForooshandeIdParameter, fldFunctionNameParameter, fldkh_Pas_NoParameter, fldkh_TypeFlyParameter, fldF_Sh_ParvaneParameter, fldF_GomrokCodeParameter, fldF_UniqIdParameter, fldShomareFishParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_tblSooratHesab_HeaderSelect> prs_tblSooratHesab_HeaderSelect(string fieldname, string value, string value1, string value2, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var value1Parameter = value1 != null ?
                new ObjectParameter("Value1", value1) :
                new ObjectParameter("Value1", typeof(string));
    
            var value2Parameter = value2 != null ?
                new ObjectParameter("value2", value2) :
                new ObjectParameter("value2", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblSooratHesab_HeaderSelect>("prs_tblSooratHesab_HeaderSelect", fieldnameParameter, valueParameter, value1Parameter, value2Parameter, hParameter);
        }
    
        public virtual int prs_tblSooratHesab_HeaderDelete(Nullable<long> fldId, Nullable<long> flduserId, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var flduserIdParameter = flduserId.HasValue ?
                new ObjectParameter("flduserId", flduserId) :
                new ObjectParameter("flduserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_HeaderDelete", fldIdParameter, flduserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_tblSooratHesabStatusInsert> prs_tblSooratHesabStatusInsert(Nullable<long> fldHeaderId, Nullable<byte> fldStatus, string fldMatn, string fldReferenceNumber, string fldSerializeObject, string fldUID, Nullable<long> fldUserId, string fldIP)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(byte));
    
            var fldMatnParameter = fldMatn != null ?
                new ObjectParameter("fldMatn", fldMatn) :
                new ObjectParameter("fldMatn", typeof(string));
    
            var fldReferenceNumberParameter = fldReferenceNumber != null ?
                new ObjectParameter("fldReferenceNumber", fldReferenceNumber) :
                new ObjectParameter("fldReferenceNumber", typeof(string));
    
            var fldSerializeObjectParameter = fldSerializeObject != null ?
                new ObjectParameter("fldSerializeObject", fldSerializeObject) :
                new ObjectParameter("fldSerializeObject", typeof(string));
    
            var fldUIDParameter = fldUID != null ?
                new ObjectParameter("fldUID", fldUID) :
                new ObjectParameter("fldUID", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblSooratHesabStatusInsert>("prs_tblSooratHesabStatusInsert", fldHeaderIdParameter, fldStatusParameter, fldMatnParameter, fldReferenceNumberParameter, fldSerializeObjectParameter, fldUIDParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_rptSooratHesab_Header> prs_rptSooratHesab_Header(Nullable<long> fldIdSooratHesab)
        {
            var fldIdSooratHesabParameter = fldIdSooratHesab.HasValue ?
                new ObjectParameter("fldIdSooratHesab", fldIdSooratHesab) :
                new ObjectParameter("fldIdSooratHesab", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_rptSooratHesab_Header>("prs_rptSooratHesab_Header", fldIdSooratHesabParameter);
        }
    
        public virtual int prs_tblSooratHesabFromWebServiceInsert(ObjectParameter headerId, Nullable<long> fldForooshandeId, string fldkh_Name, string fldkh_Family, string fldBid, Nullable<byte> fldkh_TypeShakhsId, string fldtinb, string fldTaxId, Nullable<System.DateTime> fldIndatim, Nullable<System.DateTime> fldIndati2m, Nullable<byte> fldInty, Nullable<byte> fldInp, string fldInno, string fldIrtaxId, string fldFunctionName, Nullable<long> fldUserId, string fldDesc, string fldIP)
        {
            var fldForooshandeIdParameter = fldForooshandeId.HasValue ?
                new ObjectParameter("fldForooshandeId", fldForooshandeId) :
                new ObjectParameter("fldForooshandeId", typeof(long));
    
            var fldkh_NameParameter = fldkh_Name != null ?
                new ObjectParameter("fldkh_Name", fldkh_Name) :
                new ObjectParameter("fldkh_Name", typeof(string));
    
            var fldkh_FamilyParameter = fldkh_Family != null ?
                new ObjectParameter("fldkh_Family", fldkh_Family) :
                new ObjectParameter("fldkh_Family", typeof(string));
    
            var fldBidParameter = fldBid != null ?
                new ObjectParameter("fldBid", fldBid) :
                new ObjectParameter("fldBid", typeof(string));
    
            var fldkh_TypeShakhsIdParameter = fldkh_TypeShakhsId.HasValue ?
                new ObjectParameter("fldkh_TypeShakhsId", fldkh_TypeShakhsId) :
                new ObjectParameter("fldkh_TypeShakhsId", typeof(byte));
    
            var fldtinbParameter = fldtinb != null ?
                new ObjectParameter("fldtinb", fldtinb) :
                new ObjectParameter("fldtinb", typeof(string));
    
            var fldTaxIdParameter = fldTaxId != null ?
                new ObjectParameter("fldTaxId", fldTaxId) :
                new ObjectParameter("fldTaxId", typeof(string));
    
            var fldIndatimParameter = fldIndatim.HasValue ?
                new ObjectParameter("fldIndatim", fldIndatim) :
                new ObjectParameter("fldIndatim", typeof(System.DateTime));
    
            var fldIndati2mParameter = fldIndati2m.HasValue ?
                new ObjectParameter("fldIndati2m", fldIndati2m) :
                new ObjectParameter("fldIndati2m", typeof(System.DateTime));
    
            var fldIntyParameter = fldInty.HasValue ?
                new ObjectParameter("fldInty", fldInty) :
                new ObjectParameter("fldInty", typeof(byte));
    
            var fldInpParameter = fldInp.HasValue ?
                new ObjectParameter("fldInp", fldInp) :
                new ObjectParameter("fldInp", typeof(byte));
    
            var fldInnoParameter = fldInno != null ?
                new ObjectParameter("fldInno", fldInno) :
                new ObjectParameter("fldInno", typeof(string));
    
            var fldIrtaxIdParameter = fldIrtaxId != null ?
                new ObjectParameter("fldIrtaxId", fldIrtaxId) :
                new ObjectParameter("fldIrtaxId", typeof(string));
    
            var fldFunctionNameParameter = fldFunctionName != null ?
                new ObjectParameter("fldFunctionName", fldFunctionName) :
                new ObjectParameter("fldFunctionName", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabFromWebServiceInsert", headerId, fldForooshandeIdParameter, fldkh_NameParameter, fldkh_FamilyParameter, fldBidParameter, fldkh_TypeShakhsIdParameter, fldtinbParameter, fldTaxIdParameter, fldIndatimParameter, fldIndati2mParameter, fldIntyParameter, fldInpParameter, fldInnoParameter, fldIrtaxIdParameter, fldFunctionNameParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_InsertSooratHesabForExcel(ObjectParameter headerId, Nullable<long> fldForooshandeId, string fldkh_Name, string fldkh_Family, string fldBid, Nullable<byte> fldkh_TypeShakhsId, string fldtinb, string fldTaxId, Nullable<System.DateTime> fldIndatim, Nullable<System.DateTime> fldIndati2m, Nullable<byte> fldInty, Nullable<byte> fldInp, string fldInno, string fldIrtaxId, string fldFunctionName, string fldShomareFish, Nullable<long> fldUserId, string fldDesc, string fldIP)
        {
            var fldForooshandeIdParameter = fldForooshandeId.HasValue ?
                new ObjectParameter("fldForooshandeId", fldForooshandeId) :
                new ObjectParameter("fldForooshandeId", typeof(long));
    
            var fldkh_NameParameter = fldkh_Name != null ?
                new ObjectParameter("fldkh_Name", fldkh_Name) :
                new ObjectParameter("fldkh_Name", typeof(string));
    
            var fldkh_FamilyParameter = fldkh_Family != null ?
                new ObjectParameter("fldkh_Family", fldkh_Family) :
                new ObjectParameter("fldkh_Family", typeof(string));
    
            var fldBidParameter = fldBid != null ?
                new ObjectParameter("fldBid", fldBid) :
                new ObjectParameter("fldBid", typeof(string));
    
            var fldkh_TypeShakhsIdParameter = fldkh_TypeShakhsId.HasValue ?
                new ObjectParameter("fldkh_TypeShakhsId", fldkh_TypeShakhsId) :
                new ObjectParameter("fldkh_TypeShakhsId", typeof(byte));
    
            var fldtinbParameter = fldtinb != null ?
                new ObjectParameter("fldtinb", fldtinb) :
                new ObjectParameter("fldtinb", typeof(string));
    
            var fldTaxIdParameter = fldTaxId != null ?
                new ObjectParameter("fldTaxId", fldTaxId) :
                new ObjectParameter("fldTaxId", typeof(string));
    
            var fldIndatimParameter = fldIndatim.HasValue ?
                new ObjectParameter("fldIndatim", fldIndatim) :
                new ObjectParameter("fldIndatim", typeof(System.DateTime));
    
            var fldIndati2mParameter = fldIndati2m.HasValue ?
                new ObjectParameter("fldIndati2m", fldIndati2m) :
                new ObjectParameter("fldIndati2m", typeof(System.DateTime));
    
            var fldIntyParameter = fldInty.HasValue ?
                new ObjectParameter("fldInty", fldInty) :
                new ObjectParameter("fldInty", typeof(byte));
    
            var fldInpParameter = fldInp.HasValue ?
                new ObjectParameter("fldInp", fldInp) :
                new ObjectParameter("fldInp", typeof(byte));
    
            var fldInnoParameter = fldInno != null ?
                new ObjectParameter("fldInno", fldInno) :
                new ObjectParameter("fldInno", typeof(string));
    
            var fldIrtaxIdParameter = fldIrtaxId != null ?
                new ObjectParameter("fldIrtaxId", fldIrtaxId) :
                new ObjectParameter("fldIrtaxId", typeof(string));
    
            var fldFunctionNameParameter = fldFunctionName != null ?
                new ObjectParameter("fldFunctionName", fldFunctionName) :
                new ObjectParameter("fldFunctionName", typeof(string));
    
            var fldShomareFishParameter = fldShomareFish != null ?
                new ObjectParameter("fldShomareFish", fldShomareFish) :
                new ObjectParameter("fldShomareFish", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_InsertSooratHesabForExcel", headerId, fldForooshandeIdParameter, fldkh_NameParameter, fldkh_FamilyParameter, fldBidParameter, fldkh_TypeShakhsIdParameter, fldtinbParameter, fldTaxIdParameter, fldIndatimParameter, fldIndati2mParameter, fldIntyParameter, fldInpParameter, fldInnoParameter, fldIrtaxIdParameter, fldFunctionNameParameter, fldShomareFishParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_TransactionInfInsert(Nullable<int> fldTarfGharardadId, string fldUserName, string fldPass, Nullable<long> fldUserId, string fldDesc, Nullable<bool> fldInherit)
        {
            var fldTarfGharardadIdParameter = fldTarfGharardadId.HasValue ?
                new ObjectParameter("fldTarfGharardadId", fldTarfGharardadId) :
                new ObjectParameter("fldTarfGharardadId", typeof(int));
    
            var fldUserNameParameter = fldUserName != null ?
                new ObjectParameter("fldUserName", fldUserName) :
                new ObjectParameter("fldUserName", typeof(string));
    
            var fldPassParameter = fldPass != null ?
                new ObjectParameter("fldPass", fldPass) :
                new ObjectParameter("fldPass", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldInheritParameter = fldInherit.HasValue ?
                new ObjectParameter("fldInherit", fldInherit) :
                new ObjectParameter("fldInherit", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_TransactionInfInsert", fldTarfGharardadIdParameter, fldUserNameParameter, fldPassParameter, fldUserIdParameter, fldDescParameter, fldInheritParameter);
        }
    
        public virtual ObjectResult<prs_TransactionInfSelect> prs_TransactionInfSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_TransactionInfSelect>("prs_TransactionInfSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_TransactionInfUpdate(Nullable<int> fldId, string fldUserName, Nullable<int> fldTarfGharardadId, string fldPass, Nullable<long> fldUserId, string fldDesc, Nullable<bool> fldInherit)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserNameParameter = fldUserName != null ?
                new ObjectParameter("fldUserName", fldUserName) :
                new ObjectParameter("fldUserName", typeof(string));
    
            var fldTarfGharardadIdParameter = fldTarfGharardadId.HasValue ?
                new ObjectParameter("fldTarfGharardadId", fldTarfGharardadId) :
                new ObjectParameter("fldTarfGharardadId", typeof(int));
    
            var fldPassParameter = fldPass != null ?
                new ObjectParameter("fldPass", fldPass) :
                new ObjectParameter("fldPass", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldInheritParameter = fldInherit.HasValue ?
                new ObjectParameter("fldInherit", fldInherit) :
                new ObjectParameter("fldInherit", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_TransactionInfUpdate", fldIdParameter, fldUserNameParameter, fldTarfGharardadIdParameter, fldPassParameter, fldUserIdParameter, fldDescParameter, fldInheritParameter);
        }
    
        public virtual int prs_tblSooratHesabHeader_ValueUpdate(Nullable<long> fldHeaderId, string fldValue, Nullable<short> fldParametrHeaderId, Nullable<long> fldUserId, string fldIP)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldParametrHeaderIdParameter = fldParametrHeaderId.HasValue ?
                new ObjectParameter("fldParametrHeaderId", fldParametrHeaderId) :
                new ObjectParameter("fldParametrHeaderId", typeof(short));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabHeader_ValueUpdate", fldHeaderIdParameter, fldValueParameter, fldParametrHeaderIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_tblSooratHesabExcelTemplateSelect> prs_tblSooratHesabExcelTemplateSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblSooratHesabExcelTemplateSelect>("prs_tblSooratHesabExcelTemplateSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<prs_tblSooratHesabExcelField_TemplateSelect> prs_tblSooratHesabExcelField_TemplateSelect(string fieldname, string value, string value1, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var value1Parameter = value1 != null ?
                new ObjectParameter("value1", value1) :
                new ObjectParameter("value1", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblSooratHesabExcelField_TemplateSelect>("prs_tblSooratHesabExcelField_TemplateSelect", fieldnameParameter, valueParameter, value1Parameter, hParameter);
        }
    
        public virtual ObjectResult<prs_SelectParametr_Field_Template> prs_SelectParametr_Field_Template(Nullable<int> templateId)
        {
            var templateIdParameter = templateId.HasValue ?
                new ObjectParameter("TemplateId", templateId) :
                new ObjectParameter("TemplateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_SelectParametr_Field_Template>("prs_SelectParametr_Field_Template", templateIdParameter);
        }
    
        public virtual int prs_tblSooratHesabExcelField_TemplateDelete(Nullable<int> fldTemplateId, Nullable<long> fldUserId, string fldIP)
        {
            var fldTemplateIdParameter = fldTemplateId.HasValue ?
                new ObjectParameter("fldTemplateId", fldTemplateId) :
                new ObjectParameter("fldTemplateId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabExcelField_TemplateDelete", fldTemplateIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesabExcelField_TemplateInsert(Nullable<int> fldTemplateId, Nullable<short> fldParametrId, Nullable<short> fldColumnNum, Nullable<long> fldUserId, string fldDesc, string fldIP)
        {
            var fldTemplateIdParameter = fldTemplateId.HasValue ?
                new ObjectParameter("fldTemplateId", fldTemplateId) :
                new ObjectParameter("fldTemplateId", typeof(int));
    
            var fldParametrIdParameter = fldParametrId.HasValue ?
                new ObjectParameter("fldParametrId", fldParametrId) :
                new ObjectParameter("fldParametrId", typeof(short));
    
            var fldColumnNumParameter = fldColumnNum.HasValue ?
                new ObjectParameter("fldColumnNum", fldColumnNum) :
                new ObjectParameter("fldColumnNum", typeof(short));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabExcelField_TemplateInsert", fldTemplateIdParameter, fldParametrIdParameter, fldColumnNumParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesabExcelField_TemplateUpdate(Nullable<long> fldId, Nullable<int> fldTemplateId, Nullable<short> fldParametrId, Nullable<short> fldColumnNum, Nullable<long> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var fldTemplateIdParameter = fldTemplateId.HasValue ?
                new ObjectParameter("fldTemplateId", fldTemplateId) :
                new ObjectParameter("fldTemplateId", typeof(int));
    
            var fldParametrIdParameter = fldParametrId.HasValue ?
                new ObjectParameter("fldParametrId", fldParametrId) :
                new ObjectParameter("fldParametrId", typeof(short));
    
            var fldColumnNumParameter = fldColumnNum.HasValue ?
                new ObjectParameter("fldColumnNum", fldColumnNum) :
                new ObjectParameter("fldColumnNum", typeof(short));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabExcelField_TemplateUpdate", fldIdParameter, fldTemplateIdParameter, fldParametrIdParameter, fldColumnNumParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesabExcelTemplateDelete(Nullable<int> fldId, Nullable<long> fldUserId, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabExcelTemplateDelete", fldIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesabExcelTemplateInsert(ObjectParameter fldid, string fldTitle, Nullable<byte> fldStartRowNumber, Nullable<long> fldUserId, string fldDesc, string fldIP)
        {
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldStartRowNumberParameter = fldStartRowNumber.HasValue ?
                new ObjectParameter("fldStartRowNumber", fldStartRowNumber) :
                new ObjectParameter("fldStartRowNumber", typeof(byte));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabExcelTemplateInsert", fldid, fldTitleParameter, fldStartRowNumberParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesabExcelTemplateUpdate(Nullable<int> fldId, string fldTitle, Nullable<byte> fldStartRowNumber, Nullable<long> fldUserId, string fldDesc, string fldIP)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldTitleParameter = fldTitle != null ?
                new ObjectParameter("fldTitle", fldTitle) :
                new ObjectParameter("fldTitle", typeof(string));
    
            var fldStartRowNumberParameter = fldStartRowNumber.HasValue ?
                new ObjectParameter("fldStartRowNumber", fldStartRowNumber) :
                new ObjectParameter("fldStartRowNumber", typeof(byte));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabExcelTemplateUpdate", fldIdParameter, fldTitleParameter, fldStartRowNumberParameter, fldUserIdParameter, fldDescParameter, fldIPParameter);
        }
    
        public virtual int prs_User_GharardadResetPass(Nullable<long> fldID, string fldPassword)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(long));
    
            var fldPasswordParameter = fldPassword != null ?
                new ObjectParameter("fldPassword", fldPassword) :
                new ObjectParameter("fldPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_User_GharardadResetPass", fldIDParameter, fldPasswordParameter);
        }
    
        public virtual ObjectResult<prs_tblSooratHesabStatusSelect> prs_tblSooratHesabStatusSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblSooratHesabStatusSelect>("prs_tblSooratHesabStatusSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_tblSooratHesab_HeaderUpdate(Nullable<long> fldid, string fldTaxId, Nullable<System.DateTime> fldIndatim, Nullable<System.DateTime> fldIndati2m, Nullable<byte> fldInty, Nullable<byte> fldInp, string fldInno, string fldIrtaxId, Nullable<long> fldKharidarId, Nullable<long> fldForooshandeId, string fldFunctionName, string fldkh_Pas_No, Nullable<byte> fldkh_TypeFly, string fldF_Sh_Parvane, string fldF_GomrokCode, string fldF_UniqId, string fldShomareFish, Nullable<long> fldUserId, string fldIP)
        {
            var fldidParameter = fldid.HasValue ?
                new ObjectParameter("fldid", fldid) :
                new ObjectParameter("fldid", typeof(long));
    
            var fldTaxIdParameter = fldTaxId != null ?
                new ObjectParameter("fldTaxId", fldTaxId) :
                new ObjectParameter("fldTaxId", typeof(string));
    
            var fldIndatimParameter = fldIndatim.HasValue ?
                new ObjectParameter("fldIndatim", fldIndatim) :
                new ObjectParameter("fldIndatim", typeof(System.DateTime));
    
            var fldIndati2mParameter = fldIndati2m.HasValue ?
                new ObjectParameter("fldIndati2m", fldIndati2m) :
                new ObjectParameter("fldIndati2m", typeof(System.DateTime));
    
            var fldIntyParameter = fldInty.HasValue ?
                new ObjectParameter("fldInty", fldInty) :
                new ObjectParameter("fldInty", typeof(byte));
    
            var fldInpParameter = fldInp.HasValue ?
                new ObjectParameter("fldInp", fldInp) :
                new ObjectParameter("fldInp", typeof(byte));
    
            var fldInnoParameter = fldInno != null ?
                new ObjectParameter("fldInno", fldInno) :
                new ObjectParameter("fldInno", typeof(string));
    
            var fldIrtaxIdParameter = fldIrtaxId != null ?
                new ObjectParameter("fldIrtaxId", fldIrtaxId) :
                new ObjectParameter("fldIrtaxId", typeof(string));
    
            var fldKharidarIdParameter = fldKharidarId.HasValue ?
                new ObjectParameter("fldKharidarId", fldKharidarId) :
                new ObjectParameter("fldKharidarId", typeof(long));
    
            var fldForooshandeIdParameter = fldForooshandeId.HasValue ?
                new ObjectParameter("fldForooshandeId", fldForooshandeId) :
                new ObjectParameter("fldForooshandeId", typeof(long));
    
            var fldFunctionNameParameter = fldFunctionName != null ?
                new ObjectParameter("fldFunctionName", fldFunctionName) :
                new ObjectParameter("fldFunctionName", typeof(string));
    
            var fldkh_Pas_NoParameter = fldkh_Pas_No != null ?
                new ObjectParameter("fldkh_Pas_No", fldkh_Pas_No) :
                new ObjectParameter("fldkh_Pas_No", typeof(string));
    
            var fldkh_TypeFlyParameter = fldkh_TypeFly.HasValue ?
                new ObjectParameter("fldkh_TypeFly", fldkh_TypeFly) :
                new ObjectParameter("fldkh_TypeFly", typeof(byte));
    
            var fldF_Sh_ParvaneParameter = fldF_Sh_Parvane != null ?
                new ObjectParameter("fldF_Sh_Parvane", fldF_Sh_Parvane) :
                new ObjectParameter("fldF_Sh_Parvane", typeof(string));
    
            var fldF_GomrokCodeParameter = fldF_GomrokCode != null ?
                new ObjectParameter("fldF_GomrokCode", fldF_GomrokCode) :
                new ObjectParameter("fldF_GomrokCode", typeof(string));
    
            var fldF_UniqIdParameter = fldF_UniqId != null ?
                new ObjectParameter("fldF_UniqId", fldF_UniqId) :
                new ObjectParameter("fldF_UniqId", typeof(string));
    
            var fldShomareFishParameter = fldShomareFish != null ?
                new ObjectParameter("fldShomareFish", fldShomareFish) :
                new ObjectParameter("fldShomareFish", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_HeaderUpdate", fldidParameter, fldTaxIdParameter, fldIndatimParameter, fldIndati2mParameter, fldIntyParameter, fldInpParameter, fldInnoParameter, fldIrtaxIdParameter, fldKharidarIdParameter, fldForooshandeIdParameter, fldFunctionNameParameter, fldkh_Pas_NoParameter, fldkh_TypeFlyParameter, fldF_Sh_ParvaneParameter, fldF_GomrokCodeParameter, fldF_UniqIdParameter, fldShomareFishParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesab_DetailUpdate(Nullable<long> fldHeaderId, Nullable<long> fldUserID, string fldIP)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_DetailUpdate", fldHeaderIdParameter, fldUserIDParameter, fldIPParameter);
        }
    
        public virtual int sp_ErrorProgramInsert(ObjectParameter fldID, string fldText, Nullable<long> fldUserID, string fldDesc, Nullable<System.DateTime> fldDate, string fldUserPass)
        {
            var fldTextParameter = fldText != null ?
                new ObjectParameter("fldText", fldText) :
                new ObjectParameter("fldText", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldDateParameter = fldDate.HasValue ?
                new ObjectParameter("fldDate", fldDate) :
                new ObjectParameter("fldDate", typeof(System.DateTime));
    
            var fldUserPassParameter = fldUserPass != null ?
                new ObjectParameter("fldUserPass", fldUserPass) :
                new ObjectParameter("fldUserPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ErrorProgramInsert", fldID, fldTextParameter, fldUserIDParameter, fldDescParameter, fldDateParameter, fldUserPassParameter);
        }
    
        public virtual int prs_tblKala_KhedmatInsert(string fldCode, Nullable<byte> fldTypeShenaseId, string fldTarikh, string fldRunDate, string fldExpDate, Nullable<bool> fldSpecialOrGeneral, Nullable<bool> fldTaxableOrFree, Nullable<byte> fldVat, Nullable<byte> fldVatCustomPurposes, string fldDescriptionOfID, Nullable<bool> type)
        {
            var fldCodeParameter = fldCode != null ?
                new ObjectParameter("fldCode", fldCode) :
                new ObjectParameter("fldCode", typeof(string));
    
            var fldTypeShenaseIdParameter = fldTypeShenaseId.HasValue ?
                new ObjectParameter("fldTypeShenaseId", fldTypeShenaseId) :
                new ObjectParameter("fldTypeShenaseId", typeof(byte));
    
            var fldTarikhParameter = fldTarikh != null ?
                new ObjectParameter("fldTarikh", fldTarikh) :
                new ObjectParameter("fldTarikh", typeof(string));
    
            var fldRunDateParameter = fldRunDate != null ?
                new ObjectParameter("fldRunDate", fldRunDate) :
                new ObjectParameter("fldRunDate", typeof(string));
    
            var fldExpDateParameter = fldExpDate != null ?
                new ObjectParameter("fldExpDate", fldExpDate) :
                new ObjectParameter("fldExpDate", typeof(string));
    
            var fldSpecialOrGeneralParameter = fldSpecialOrGeneral.HasValue ?
                new ObjectParameter("fldSpecialOrGeneral", fldSpecialOrGeneral) :
                new ObjectParameter("fldSpecialOrGeneral", typeof(bool));
    
            var fldTaxableOrFreeParameter = fldTaxableOrFree.HasValue ?
                new ObjectParameter("fldTaxableOrFree", fldTaxableOrFree) :
                new ObjectParameter("fldTaxableOrFree", typeof(bool));
    
            var fldVatParameter = fldVat.HasValue ?
                new ObjectParameter("fldVat", fldVat) :
                new ObjectParameter("fldVat", typeof(byte));
    
            var fldVatCustomPurposesParameter = fldVatCustomPurposes.HasValue ?
                new ObjectParameter("fldVatCustomPurposes", fldVatCustomPurposes) :
                new ObjectParameter("fldVatCustomPurposes", typeof(byte));
    
            var fldDescriptionOfIDParameter = fldDescriptionOfID != null ?
                new ObjectParameter("fldDescriptionOfID", fldDescriptionOfID) :
                new ObjectParameter("fldDescriptionOfID", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblKala_KhedmatInsert", fldCodeParameter, fldTypeShenaseIdParameter, fldTarikhParameter, fldRunDateParameter, fldExpDateParameter, fldSpecialOrGeneralParameter, fldTaxableOrFreeParameter, fldVatParameter, fldVatCustomPurposesParameter, fldDescriptionOfIDParameter, typeParameter);
        }
    
        public virtual int prs_tblKala_KhedmatDelete(string code, Nullable<bool> type)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblKala_KhedmatDelete", codeParameter, typeParameter);
        }
    
        public virtual int prs_tblSooratHesab_DetailDelete(Nullable<long> fldId, Nullable<long> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_DetailDelete", fldIdParameter, fldUserIdParameter);
        }
    
        public virtual int prs_UpdateIrTaxId(Nullable<long> idHeader, string fldIrtaxId, Nullable<long> fldUserId, string fldIP)
        {
            var idHeaderParameter = idHeader.HasValue ?
                new ObjectParameter("IdHeader", idHeader) :
                new ObjectParameter("IdHeader", typeof(long));
    
            var fldIrtaxIdParameter = fldIrtaxId != null ?
                new ObjectParameter("fldIrtaxId", fldIrtaxId) :
                new ObjectParameter("fldIrtaxId", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_UpdateIrTaxId", idHeaderParameter, fldIrtaxIdParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual int prs_tblSooratHesabStatus_DetailInsert(Nullable<long> fldSooratHesabStatusId, Nullable<byte> fldStatusError, string fldMatn, string fldCode, Nullable<long> fldUserId, string fldIP)
        {
            var fldSooratHesabStatusIdParameter = fldSooratHesabStatusId.HasValue ?
                new ObjectParameter("fldSooratHesabStatusId", fldSooratHesabStatusId) :
                new ObjectParameter("fldSooratHesabStatusId", typeof(long));
    
            var fldStatusErrorParameter = fldStatusError.HasValue ?
                new ObjectParameter("fldStatusError", fldStatusError) :
                new ObjectParameter("fldStatusError", typeof(byte));
    
            var fldMatnParameter = fldMatn != null ?
                new ObjectParameter("fldMatn", fldMatn) :
                new ObjectParameter("fldMatn", typeof(string));
    
            var fldCodeParameter = fldCode != null ?
                new ObjectParameter("fldCode", fldCode) :
                new ObjectParameter("fldCode", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabStatus_DetailInsert", fldSooratHesabStatusIdParameter, fldStatusErrorParameter, fldMatnParameter, fldCodeParameter, fldUserIdParameter, fldIPParameter);
        }
    
        public virtual ObjectResult<prs_tblSooratHesabStatus_DetailSelect> prs_tblSooratHesabStatus_DetailSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblSooratHesabStatus_DetailSelect>("prs_tblSooratHesabStatus_DetailSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_tblSooratHesabStatusUpdate(Nullable<long> fldid, Nullable<long> fldHeaderId, Nullable<byte> fldStatus, string fldMatn, string fldReferenceNumber, string fldSerializeObject, string fldUID, Nullable<long> fldUserId, string fldIP)
        {
            var fldidParameter = fldid.HasValue ?
                new ObjectParameter("fldid", fldid) :
                new ObjectParameter("fldid", typeof(long));
    
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(byte));
    
            var fldMatnParameter = fldMatn != null ?
                new ObjectParameter("fldMatn", fldMatn) :
                new ObjectParameter("fldMatn", typeof(string));
    
            var fldReferenceNumberParameter = fldReferenceNumber != null ?
                new ObjectParameter("fldReferenceNumber", fldReferenceNumber) :
                new ObjectParameter("fldReferenceNumber", typeof(string));
    
            var fldSerializeObjectParameter = fldSerializeObject != null ?
                new ObjectParameter("fldSerializeObject", fldSerializeObject) :
                new ObjectParameter("fldSerializeObject", typeof(string));
    
            var fldUIDParameter = fldUID != null ?
                new ObjectParameter("fldUID", fldUID) :
                new ObjectParameter("fldUID", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldIPParameter = fldIP != null ?
                new ObjectParameter("fldIP", fldIP) :
                new ObjectParameter("fldIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabStatusUpdate", fldidParameter, fldHeaderIdParameter, fldStatusParameter, fldMatnParameter, fldReferenceNumberParameter, fldSerializeObjectParameter, fldUIDParameter, fldUserIdParameter, fldIPParameter);
        }
    }
}
