//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    
    public partial class prs_SelectParametr_Field_Template
    {
        public string fldNameEn { get; set; }
        public string fldNameFa { get; set; }
        public string fldColumnNum { get; set; }
        public bool fldInExcel { get; set; }
        public bool fldEjbari { get; set; }
        public short fldId { get; set; }
        public string fldEjbariName { get; set; }
    }
}
