//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    
    public partial class prs_tblSooratHesabExcelField_TemplateSelect
    {
        public long fldId { get; set; }
        public int fldTemplateId { get; set; }
        public short fldParametrId { get; set; }
        public short fldColumnNum { get; set; }
        public long fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public string fldNameEn { get; set; }
    }
}
