//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://epay.tehran.ir:443/merchantwebservice/jax/merchantAuth")]
        public string Avarez_WsCity_PaymentWebServiceService {
            get {
                return ((string)(this["Avarez_WsCity_PaymentWebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev.epishkhan.ir/nwsv1/index.php")]
        public string Avarez_ir_epishkhan_dev_dev_pishkhan_nwsv1 {
            get {
                return ((string)(this["Avarez_ir_epishkhan_dev_dev_pishkhan_nwsv1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pec.shaparak.ir/pecpaymentgateway/eshopservice.asmx")]
        public string Avarez_Parsian_EShopService {
            get {
                return ((string)(this["Avarez_Parsian_EShopService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://kica.shaparak.ir:443/epay/services")]
        public string Avarez_Tejarat_MerchantService {
            get {
                return ((string)(this["Avarez_Tejarat_MerchantService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sadad.shaparak.ir/MerchantUtility.asmx")]
        public string Avarez_WsMeli_MerchantUtility {
            get {
                return ((string)(this["Avarez_WsMeli_MerchantUtility"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bill.samanepay.com/Checkbill/BillStateService.svc")]
        public string Avarez_Saman_BillStateService {
            get {
                return ((string)(this["Avarez_Saman_BillStateService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ecartax.ir/SendToSuporter.asmx")]
        public string Avarez_Supporter_SendToSuporter {
            get {
                return ((string)(this["Avarez_Supporter_SendToSuporter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://trn.ecartax.ir/TransactionWebService.asmx")]
        public string Avarez_WebTransaction_TransactionWebService {
            get {
                return ((string)(this["Avarez_WebTransaction_TransactionWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1819/SabtWebService.svc")]
        public string Avarez_SabtWs_SabtWebService {
            get {
                return ((string)(this["Avarez_SabtWs_SabtWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.33:7011/AvarezRate.asmx")]
        public string Avarez_RateWebService_Rate {
            get {
                return ((string)(this["Avarez_RateWebService_Rate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://217.218.243.15/InternalSabtWebServise.asmx")]
        public string Avarez_InSabt_InternalSabtWebServise {
            get {
                return ((string)(this["Avarez_InSabt_InternalSabtWebServise"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://46.100.105.150:1820/estelam.asmx")]
        public string Avarez_RasaSabt_Estelam {
            get {
                return ((string)(this["Avarez_RasaSabt_Estelam"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pec.shaparak.ir/NewIPGServices/Sale/SaleService.asmx")]
        public string Avarez_Parsian_New_SaleService {
            get {
                return ((string)(this["Avarez_Parsian_New_SaleService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pec.shaparak.ir/NewIPGServices/Confirm/ConfirmService.asmx")]
        public string Avarez_ConfirmService_ConfirmService {
            get {
                return ((string)(this["Avarez_ConfirmService_ConfirmService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mabna.shaparak.ir:443/BillTokenService")]
        public string Avarez_WsCityNew_Token {
            get {
                return ((string)(this["Avarez_WsCityNew_Token"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mabna.shaparak.ir:443/TransactionReference/TransactionReference")]
        public string Avarez_WsCityNew1_TransactionReference {
            get {
                return ((string)(this["Avarez_WsCityNew1_TransactionReference"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev.epishkhan.ir/nwsv2/index.php")]
        public string Avarez_new_epishkhan_dev_pishkhan_nwsv2 {
            get {
                return ((string)(this["Avarez_new_epishkhan_dev_pishkhan_nwsv2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://poswsappdev.epishkhan.ir:5380/index.php")]
        public string Avarez_epishkhan_pos_dev_pishkhan_posws {
            get {
                return ((string)(this["Avarez_epishkhan_pos_dev_pishkhan_posws"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://78.38.56.21:8001/UssdService.asmx")]
        public string Avarez_ussd_UssdService {
            get {
                return ((string)(this["Avarez_ussd_UssdService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sep.shaparak.ir/payments/referencepayment.asmx")]
        public string Avarez_Saman_New_PaymentIFBinding {
            get {
                return ((string)(this["Avarez_Saman_New_PaymentIFBinding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://46.209.114.102:81/Revenue/Services/ServiseToRevenueSystems.asmx")]
        public string Avarez_Hesabrayan_ServiseToRevenueSystems {
            get {
                return ((string)(this["Avarez_Hesabrayan_ServiseToRevenueSystems"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:20171/Service1.svc")]
        public string Avarez_SamieSrv_Service1 {
            get {
                return ((string)(this["Avarez_SamieSrv_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sms.ecartax.ir/RasaSmsPanel_send.asmx")]
        public string Avarez_SmsPanel_RasaSMSPanel_Send {
            get {
                return ((string)(this["Avarez_SmsPanel_RasaSMSPanel_Send"]));
            }
        }
    }
}
