//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Avarez.RasaSabt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EstelamSoap", Namespace="http://tempuri.org/")]
    public partial class Estelam : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CodeMeliOperationCompleted;
        
        private System.Threading.SendOrPostCallback OldNationalCardPhotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewNationalCardPhotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressFromPostalCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddressFromTeloghonOperationCompleted;
        
        private System.Threading.SendOrPostCallback MilitaryStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Estelam() {
            this.Url = global::Avarez.Properties.Settings.Default.Avarez_RasaSabt_Estelam;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CodeMeliCompletedEventHandler CodeMeliCompleted;
        
        /// <remarks/>
        public event OldNationalCardPhotoCompletedEventHandler OldNationalCardPhotoCompleted;
        
        /// <remarks/>
        public event NewNationalCardPhotoCompletedEventHandler NewNationalCardPhotoCompleted;
        
        /// <remarks/>
        public event AddressFromPostalCodeCompletedEventHandler AddressFromPostalCodeCompleted;
        
        /// <remarks/>
        public event AddressFromTeloghonCompletedEventHandler AddressFromTeloghonCompleted;
        
        /// <remarks/>
        public event MilitaryStatusCompletedEventHandler MilitaryStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CodeMeli", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sp_tblPersons CodeMeli([System.Xml.Serialization.XmlElementAttribute("codemeli")] string codemeli1, string birthDate, bool live, string UserName, string Pass, out string Error) {
            object[] results = this.Invoke("CodeMeli", new object[] {
                        codemeli1,
                        birthDate,
                        live,
                        UserName,
                        Pass});
            Error = ((string)(results[1]));
            return ((Sp_tblPersons)(results[0]));
        }
        
        /// <remarks/>
        public void CodeMeliAsync(string codemeli1, string birthDate, bool live, string UserName, string Pass) {
            this.CodeMeliAsync(codemeli1, birthDate, live, UserName, Pass, null);
        }
        
        /// <remarks/>
        public void CodeMeliAsync(string codemeli1, string birthDate, bool live, string UserName, string Pass, object userState) {
            if ((this.CodeMeliOperationCompleted == null)) {
                this.CodeMeliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCodeMeliOperationCompleted);
            }
            this.InvokeAsync("CodeMeli", new object[] {
                        codemeli1,
                        birthDate,
                        live,
                        UserName,
                        Pass}, this.CodeMeliOperationCompleted, userState);
        }
        
        private void OnCodeMeliOperationCompleted(object arg) {
            if ((this.CodeMeliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CodeMeliCompleted(this, new CodeMeliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OldNationalCardPhoto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] OldNationalCardPhoto(string NationalCode, string CardSeri, string CardSerial, bool Live, string UserName, string Pass, out string Error) {
            object[] results = this.Invoke("OldNationalCardPhoto", new object[] {
                        NationalCode,
                        CardSeri,
                        CardSerial,
                        Live,
                        UserName,
                        Pass});
            Error = ((string)(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void OldNationalCardPhotoAsync(string NationalCode, string CardSeri, string CardSerial, bool Live, string UserName, string Pass) {
            this.OldNationalCardPhotoAsync(NationalCode, CardSeri, CardSerial, Live, UserName, Pass, null);
        }
        
        /// <remarks/>
        public void OldNationalCardPhotoAsync(string NationalCode, string CardSeri, string CardSerial, bool Live, string UserName, string Pass, object userState) {
            if ((this.OldNationalCardPhotoOperationCompleted == null)) {
                this.OldNationalCardPhotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOldNationalCardPhotoOperationCompleted);
            }
            this.InvokeAsync("OldNationalCardPhoto", new object[] {
                        NationalCode,
                        CardSeri,
                        CardSerial,
                        Live,
                        UserName,
                        Pass}, this.OldNationalCardPhotoOperationCompleted, userState);
        }
        
        private void OnOldNationalCardPhotoOperationCompleted(object arg) {
            if ((this.OldNationalCardPhotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OldNationalCardPhotoCompleted(this, new OldNationalCardPhotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewNationalCardPhoto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] NewNationalCardPhoto(string NationalCode, string CardSerial, bool Live, string UserName, string Pass, out string Error) {
            object[] results = this.Invoke("NewNationalCardPhoto", new object[] {
                        NationalCode,
                        CardSerial,
                        Live,
                        UserName,
                        Pass});
            Error = ((string)(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void NewNationalCardPhotoAsync(string NationalCode, string CardSerial, bool Live, string UserName, string Pass) {
            this.NewNationalCardPhotoAsync(NationalCode, CardSerial, Live, UserName, Pass, null);
        }
        
        /// <remarks/>
        public void NewNationalCardPhotoAsync(string NationalCode, string CardSerial, bool Live, string UserName, string Pass, object userState) {
            if ((this.NewNationalCardPhotoOperationCompleted == null)) {
                this.NewNationalCardPhotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewNationalCardPhotoOperationCompleted);
            }
            this.InvokeAsync("NewNationalCardPhoto", new object[] {
                        NationalCode,
                        CardSerial,
                        Live,
                        UserName,
                        Pass}, this.NewNationalCardPhotoOperationCompleted, userState);
        }
        
        private void OnNewNationalCardPhotoOperationCompleted(object arg) {
            if ((this.NewNationalCardPhotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewNationalCardPhotoCompleted(this, new NewNationalCardPhotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddressFromPostalCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sp_tblResponse AddressFromPostalCode(string codePosti, bool Live, string UserName, string Pass, out string Error) {
            object[] results = this.Invoke("AddressFromPostalCode", new object[] {
                        codePosti,
                        Live,
                        UserName,
                        Pass});
            Error = ((string)(results[1]));
            return ((Sp_tblResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddressFromPostalCodeAsync(string codePosti, bool Live, string UserName, string Pass) {
            this.AddressFromPostalCodeAsync(codePosti, Live, UserName, Pass, null);
        }
        
        /// <remarks/>
        public void AddressFromPostalCodeAsync(string codePosti, bool Live, string UserName, string Pass, object userState) {
            if ((this.AddressFromPostalCodeOperationCompleted == null)) {
                this.AddressFromPostalCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressFromPostalCodeOperationCompleted);
            }
            this.InvokeAsync("AddressFromPostalCode", new object[] {
                        codePosti,
                        Live,
                        UserName,
                        Pass}, this.AddressFromPostalCodeOperationCompleted, userState);
        }
        
        private void OnAddressFromPostalCodeOperationCompleted(object arg) {
            if ((this.AddressFromPostalCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressFromPostalCodeCompleted(this, new AddressFromPostalCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddressFromTeloghon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sp_tblResponse AddressFromTeloghon(string preTelephoneNo, string telephoneNo, bool Live, string UserName, string Pass, out string Error) {
            object[] results = this.Invoke("AddressFromTeloghon", new object[] {
                        preTelephoneNo,
                        telephoneNo,
                        Live,
                        UserName,
                        Pass});
            Error = ((string)(results[1]));
            return ((Sp_tblResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddressFromTeloghonAsync(string preTelephoneNo, string telephoneNo, bool Live, string UserName, string Pass) {
            this.AddressFromTeloghonAsync(preTelephoneNo, telephoneNo, Live, UserName, Pass, null);
        }
        
        /// <remarks/>
        public void AddressFromTeloghonAsync(string preTelephoneNo, string telephoneNo, bool Live, string UserName, string Pass, object userState) {
            if ((this.AddressFromTeloghonOperationCompleted == null)) {
                this.AddressFromTeloghonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddressFromTeloghonOperationCompleted);
            }
            this.InvokeAsync("AddressFromTeloghon", new object[] {
                        preTelephoneNo,
                        telephoneNo,
                        Live,
                        UserName,
                        Pass}, this.AddressFromTeloghonOperationCompleted, userState);
        }
        
        private void OnAddressFromTeloghonOperationCompleted(object arg) {
            if ((this.AddressFromTeloghonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddressFromTeloghonCompleted(this, new AddressFromTeloghonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MilitaryStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sp_tblMilitary MilitaryStatus(string codemeli, bool Live, string UserName, string Pass, out string Error) {
            object[] results = this.Invoke("MilitaryStatus", new object[] {
                        codemeli,
                        Live,
                        UserName,
                        Pass});
            Error = ((string)(results[1]));
            return ((Sp_tblMilitary)(results[0]));
        }
        
        /// <remarks/>
        public void MilitaryStatusAsync(string codemeli, bool Live, string UserName, string Pass) {
            this.MilitaryStatusAsync(codemeli, Live, UserName, Pass, null);
        }
        
        /// <remarks/>
        public void MilitaryStatusAsync(string codemeli, bool Live, string UserName, string Pass, object userState) {
            if ((this.MilitaryStatusOperationCompleted == null)) {
                this.MilitaryStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMilitaryStatusOperationCompleted);
            }
            this.InvokeAsync("MilitaryStatus", new object[] {
                        codemeli,
                        Live,
                        UserName,
                        Pass}, this.MilitaryStatusOperationCompleted, userState);
        }
        
        private void OnMilitaryStatusOperationCompleted(object arg) {
            if ((this.MilitaryStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MilitaryStatusCompleted(this, new MilitaryStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sp_tblPersons {
        
        private int idField;
        
        private string birthDateField;
        
        private string bookNoField;
        
        private string bookRowField;
        
        private string deathStatusField;
        
        private string familyField;
        
        private string fatherNameField;
        
        private string genderField;
        
        private string messageField;
        
        private string nameField;
        
        private string ninField;
        
        private string officeCodeField;
        
        private string officeNameField;
        
        private string shenasnameNoField;
        
        private string shenasnameSeriField;
        
        private string shenasnameSerialField;
        
        private string genderNameField;
        
        private string deathStatusNameField;
        
        private System.Nullable<int> userWebField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string bookNo {
            get {
                return this.bookNoField;
            }
            set {
                this.bookNoField = value;
            }
        }
        
        /// <remarks/>
        public string bookRow {
            get {
                return this.bookRowField;
            }
            set {
                this.bookRowField = value;
            }
        }
        
        /// <remarks/>
        public string deathStatus {
            get {
                return this.deathStatusField;
            }
            set {
                this.deathStatusField = value;
            }
        }
        
        /// <remarks/>
        public string family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public string fatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string nin {
            get {
                return this.ninField;
            }
            set {
                this.ninField = value;
            }
        }
        
        /// <remarks/>
        public string officeCode {
            get {
                return this.officeCodeField;
            }
            set {
                this.officeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string officeName {
            get {
                return this.officeNameField;
            }
            set {
                this.officeNameField = value;
            }
        }
        
        /// <remarks/>
        public string shenasnameNo {
            get {
                return this.shenasnameNoField;
            }
            set {
                this.shenasnameNoField = value;
            }
        }
        
        /// <remarks/>
        public string shenasnameSeri {
            get {
                return this.shenasnameSeriField;
            }
            set {
                this.shenasnameSeriField = value;
            }
        }
        
        /// <remarks/>
        public string shenasnameSerial {
            get {
                return this.shenasnameSerialField;
            }
            set {
                this.shenasnameSerialField = value;
            }
        }
        
        /// <remarks/>
        public string genderName {
            get {
                return this.genderNameField;
            }
            set {
                this.genderNameField = value;
            }
        }
        
        /// <remarks/>
        public string deathStatusName {
            get {
                return this.deathStatusNameField;
            }
            set {
                this.deathStatusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UserWeb {
            get {
                return this.userWebField;
            }
            set {
                this.userWebField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sp_tblMilitary {
        
        private int idField;
        
        private string nationalCodeField;
        
        private string resulteField;
        
        private string descriptionField;
        
        private int userWebField;
        
        private string nameResulteField;
        
        private System.DateTime c_dateField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string NationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Resulte {
            get {
                return this.resulteField;
            }
            set {
                this.resulteField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int UserWeb {
            get {
                return this.userWebField;
            }
            set {
                this.userWebField = value;
            }
        }
        
        /// <remarks/>
        public string NameResulte {
            get {
                return this.nameResulteField;
            }
            set {
                this.nameResulteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime C_date {
            get {
                return this.c_dateField;
            }
            set {
                this.c_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sp_tblResponse {
        
        private int idField;
        
        private string locationField;
        
        private string locationTypeField;
        
        private string parishField;
        
        private string preAvenueField;
        
        private string sideFloorField;
        
        private string stateField;
        
        private string townShipField;
        
        private string villageField;
        
        private string zoneField;
        
        private string descriptionField;
        
        private string locationCodeField;
        
        private string postcodeField;
        
        private string telNoField;
        
        private string preTelNoField;
        
        private string floorNoField;
        
        private string avenueField;
        
        private string houseNoField;
        
        private string buildingNameField;
        
        private int userWebField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string locationType {
            get {
                return this.locationTypeField;
            }
            set {
                this.locationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string parish {
            get {
                return this.parishField;
            }
            set {
                this.parishField = value;
            }
        }
        
        /// <remarks/>
        public string preAvenue {
            get {
                return this.preAvenueField;
            }
            set {
                this.preAvenueField = value;
            }
        }
        
        /// <remarks/>
        public string sideFloor {
            get {
                return this.sideFloorField;
            }
            set {
                this.sideFloorField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string townShip {
            get {
                return this.townShipField;
            }
            set {
                this.townShipField = value;
            }
        }
        
        /// <remarks/>
        public string village {
            get {
                return this.villageField;
            }
            set {
                this.villageField = value;
            }
        }
        
        /// <remarks/>
        public string zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string locationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string TelNo {
            get {
                return this.telNoField;
            }
            set {
                this.telNoField = value;
            }
        }
        
        /// <remarks/>
        public string PreTelNo {
            get {
                return this.preTelNoField;
            }
            set {
                this.preTelNoField = value;
            }
        }
        
        /// <remarks/>
        public string floorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
            }
        }
        
        /// <remarks/>
        public string avenue {
            get {
                return this.avenueField;
            }
            set {
                this.avenueField = value;
            }
        }
        
        /// <remarks/>
        public string houseNo {
            get {
                return this.houseNoField;
            }
            set {
                this.houseNoField = value;
            }
        }
        
        /// <remarks/>
        public string buildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        public int UserWeb {
            get {
                return this.userWebField;
            }
            set {
                this.userWebField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CodeMeliCompletedEventHandler(object sender, CodeMeliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CodeMeliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CodeMeliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sp_tblPersons Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sp_tblPersons)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void OldNationalCardPhotoCompletedEventHandler(object sender, OldNationalCardPhotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OldNationalCardPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OldNationalCardPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void NewNationalCardPhotoCompletedEventHandler(object sender, NewNationalCardPhotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewNationalCardPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewNationalCardPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AddressFromPostalCodeCompletedEventHandler(object sender, AddressFromPostalCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressFromPostalCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressFromPostalCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sp_tblResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sp_tblResponse)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AddressFromTeloghonCompletedEventHandler(object sender, AddressFromTeloghonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressFromTeloghonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddressFromTeloghonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sp_tblResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sp_tblResponse)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MilitaryStatusCompletedEventHandler(object sender, MilitaryStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MilitaryStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MilitaryStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sp_tblMilitary Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sp_tblMilitary)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591