//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_City_LogSelect
    {
        public int fldID { get; set; }
        public string C_شهرنام { get; set; }
        public int fldZoneID { get; set; }
        public int fldUserID { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public int fldTypeLogID { get; set; }
        public int fldLogID { get; set; }
        public string نام_بخش_ { get; set; }
        public string کاربرایجادکننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
