//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_ComplicationsRate_LogSelect
    {
        public long fldID { get; set; }
        public Nullable<short> سال { get; set; }
        public Nullable<byte> از_سیلندر { get; set; }
        public Nullable<byte> تا_سیلندر { get; set; }
        public Nullable<byte> از_چرخ { get; set; }
        public Nullable<byte> تا_چرخ { get; set; }
        public Nullable<short> از_مدل { get; set; }
        public Nullable<short> تا_مدل { get; set; }
        public Nullable<int> از_حجم_موتور { get; set; }
        public Nullable<int> تا_حجم_موتور { get; set; }
        public int مبلغ { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string تقسیمات_کشوری { get; set; }
        public string کاربرایجادکننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
