//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_ImplementationFinesRuleSelect
    {
        public int fldID { get; set; }
        public int fldFinesRuleID { get; set; }
        public string fldCarSeriesName { get; set; }
        public long fldCarSeriesID { get; set; }
        public string fldCountryDivisionName { get; set; }
        public long fldCountryDivisionID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldFineRuleName { get; set; }
        public string fldImplementationDate { get; set; }
        public Nullable<float> fldPercentFine { get; set; }
        public string fldCarSeriesTreeApply { get; set; }
        public string fldCountryDivisionsTreeApply { get; set; }
        public Nullable<bool> fldCarSeriesTreeApplyBit { get; set; }
        public Nullable<bool> fldCountryDivisionsTreeApplyBit { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryType { get; set; }
        public Nullable<int> CarCode { get; set; }
        public Nullable<int> CarType { get; set; }
    }
}
