//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_MainSetting_LogSelect
    {
        public int fldID { get; set; }
        public string اخد_جریمه_دیرکرد { get; set; }
        public string اخذ_خودرو_فرسوده { get; set; }
        public string تاریخ_اجرا { get; set; }
        public string موقعیت { get; set; }
        public string اعمال_زیر_شاخه_موقعیت { get; set; }
        public string وسیله_نقلیه { get; set; }
        public string اعمال_زیر_شاخه { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string کاربر_ایجاد_کننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
