//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_online
    {
        public long fldID { get; set; }
        public int fldBankID { get; set; }
        public long fldPeacockeryID { get; set; }
        public string fldTemporaryCode { get; set; }
        public Nullable<bool> fldFinalPayment { get; set; }
        public string fldTrackCode { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<decimal> fldMony { get; set; }
        public Nullable<int> fldMunID { get; set; }
        public Nullable<int> fldGuestUserId { get; set; }
    }
}
