//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class Sp_Peacockery_CopySelect
    {
        public long fldId { get; set; }
        public long fldPeacockeryId { get; set; }
        public byte[] fldCopy { get; set; }
    }
}
