//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_SMSSettingSelect
    {
        public int fldID { get; set; }
        public string fldUserName { get; set; }
        public string fldPassword { get; set; }
        public string fldLineNumber { get; set; }
        public long fldCountryDivisionId { get; set; }
        public string fldCountryDivisionName { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CoutryDivisionCode { get; set; }
        public Nullable<int> CoutryDivisionType { get; set; }
    }
}
