//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_TransactionInfSelect
    {
        public int fldId { get; set; }
        public string fldUserName { get; set; }
        public long fldDivId { get; set; }
        public string fldPass { get; set; }
        public long fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryType { get; set; }
        public string fldCountryDivisionsName { get; set; }
        public bool fldInherit { get; set; }
    }
}
