//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMunicipality
    {
        public tblMunicipality()
        {
            this.tblAreas = new HashSet<tblArea>();
            this.tblBudgetByMonths = new HashSet<tblBudgetByMonth>();
            this.tblCarExperiences = new HashSet<tblCarExperience>();
            this.tblCollections = new HashSet<tblCollection>();
            this.tblCountryDivisions = new HashSet<tblCountryDivision>();
            this.tblDegreeMunicipalities = new HashSet<tblDegreeMunicipality>();
            this.tblLocals = new HashSet<tblLocal>();
            this.tblNews = new HashSet<tblNew>();
            this.tblOffices = new HashSet<tblOffice>();
            this.tblOnlinePayments = new HashSet<tblOnlinePayment>();
            this.tblPictures = new HashSet<tblPicture>();
            this.tblPictureMunicipalities = new HashSet<tblPictureMunicipality>();
            this.tblSignerEmployees = new HashSet<tblSignerEmployee>();
        }
    
        public int fldID { get; set; }
        public string fldName { get; set; }
        public int fldCityID { get; set; }
        public string fldInformaticesCode { get; set; }
        public byte fldServiceCode { get; set; }
        public string fldRWUserName { get; set; }
        public string fldRWPass { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
    
        public virtual ICollection<tblArea> tblAreas { get; set; }
        public virtual ICollection<tblBudgetByMonth> tblBudgetByMonths { get; set; }
        public virtual ICollection<tblCarExperience> tblCarExperiences { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual ICollection<tblCollection> tblCollections { get; set; }
        public virtual ICollection<tblCountryDivision> tblCountryDivisions { get; set; }
        public virtual ICollection<tblDegreeMunicipality> tblDegreeMunicipalities { get; set; }
        public virtual ICollection<tblLocal> tblLocals { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblNew> tblNews { get; set; }
        public virtual ICollection<tblOffice> tblOffices { get; set; }
        public virtual ICollection<tblOnlinePayment> tblOnlinePayments { get; set; }
        public virtual ICollection<tblPicture> tblPictures { get; set; }
        public virtual ICollection<tblPictureMunicipality> tblPictureMunicipalities { get; set; }
        public virtual ICollection<tblSignerEmployee> tblSignerEmployees { get; set; }
    }
}
