//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Avarez.RateWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RateSoap", Namespace="http://tempuri.org/")]
    public partial class Rate : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckAccountChargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClassOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOfficeInfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMunInfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLocalInfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarClassInfOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Rate() {
            this.Url = global::Avarez.Properties.Settings.Default.Avarez_RateWebService_Rate;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckAccountChargeCompletedEventHandler CheckAccountChargeCompleted;
        
        /// <remarks/>
        public event GetRateCompletedEventHandler GetRateCompleted;
        
        /// <remarks/>
        public event GetClassCompletedEventHandler GetClassCompleted;
        
        /// <remarks/>
        public event GetCountryCompletedEventHandler GetCountryCompleted;
        
        /// <remarks/>
        public event GetOfficeInfCompletedEventHandler GetOfficeInfCompleted;
        
        /// <remarks/>
        public event GetMunInfCompletedEventHandler GetMunInfCompleted;
        
        /// <remarks/>
        public event GetLocalInfCompletedEventHandler GetLocalInfCompleted;
        
        /// <remarks/>
        public event GetCarClassInfCompletedEventHandler GetCarClassInfCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckAccountCharge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckAccountCharge(string _User, string _Pass, string MunName) {
            object[] results = this.Invoke("CheckAccountCharge", new object[] {
                        _User,
                        _Pass,
                        MunName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckAccountChargeAsync(string _User, string _Pass, string MunName) {
            this.CheckAccountChargeAsync(_User, _Pass, MunName, null);
        }
        
        /// <remarks/>
        public void CheckAccountChargeAsync(string _User, string _Pass, string MunName, object userState) {
            if ((this.CheckAccountChargeOperationCompleted == null)) {
                this.CheckAccountChargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckAccountChargeOperationCompleted);
            }
            this.InvokeAsync("CheckAccountCharge", new object[] {
                        _User,
                        _Pass,
                        MunName}, this.CheckAccountChargeOperationCompleted, userState);
        }
        
        private void OnCheckAccountChargeOperationCompleted(object arg) {
            if ((this.CheckAccountChargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckAccountChargeCompleted(this, new CheckAccountChargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRateForWebService[] GetRate(string _User, string _Pass, string MunName, int FromYear, int ToYear, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass) {
            object[] results = this.Invoke("GetRate", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        FromYear,
                        ToYear,
                        CarMakeType,
                        CarAccountType,
                        CarCabin,
                        CarSystem,
                        CarTip,
                        CarClass});
            return ((GetRateForWebService[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRateAsync(string _User, string _Pass, string MunName, int FromYear, int ToYear, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass) {
            this.GetRateAsync(_User, _Pass, MunName, FromYear, ToYear, CarMakeType, CarAccountType, CarCabin, CarSystem, CarTip, CarClass, null);
        }
        
        /// <remarks/>
        public void GetRateAsync(string _User, string _Pass, string MunName, int FromYear, int ToYear, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass, object userState) {
            if ((this.GetRateOperationCompleted == null)) {
                this.GetRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRateOperationCompleted);
            }
            this.InvokeAsync("GetRate", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        FromYear,
                        ToYear,
                        CarMakeType,
                        CarAccountType,
                        CarCabin,
                        CarSystem,
                        CarTip,
                        CarClass}, this.GetRateOperationCompleted, userState);
        }
        
        private void OnGetRateOperationCompleted(object arg) {
            if ((this.GetRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRateCompleted(this, new GetRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetClassForWebService[] GetClass(string _User, string _Pass, string MunName, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass) {
            object[] results = this.Invoke("GetClass", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        CarMakeType,
                        CarAccountType,
                        CarCabin,
                        CarSystem,
                        CarTip,
                        CarClass});
            return ((GetClassForWebService[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClassAsync(string _User, string _Pass, string MunName, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass) {
            this.GetClassAsync(_User, _Pass, MunName, CarMakeType, CarAccountType, CarCabin, CarSystem, CarTip, CarClass, null);
        }
        
        /// <remarks/>
        public void GetClassAsync(string _User, string _Pass, string MunName, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass, object userState) {
            if ((this.GetClassOperationCompleted == null)) {
                this.GetClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassOperationCompleted);
            }
            this.InvokeAsync("GetClass", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        CarMakeType,
                        CarAccountType,
                        CarCabin,
                        CarSystem,
                        CarTip,
                        CarClass}, this.GetClassOperationCompleted, userState);
        }
        
        private void OnGetClassOperationCompleted(object arg) {
            if ((this.GetClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClassCompleted(this, new GetClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCountry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetCountryDivForWebService[] GetCountry(string _User, string _Pass, string MunName, string State, string County, string zone, string city, string Mun) {
            object[] results = this.Invoke("GetCountry", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        State,
                        County,
                        zone,
                        city,
                        Mun});
            return ((GetCountryDivForWebService[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCountryAsync(string _User, string _Pass, string MunName, string State, string County, string zone, string city, string Mun) {
            this.GetCountryAsync(_User, _Pass, MunName, State, County, zone, city, Mun, null);
        }
        
        /// <remarks/>
        public void GetCountryAsync(string _User, string _Pass, string MunName, string State, string County, string zone, string city, string Mun, object userState) {
            if ((this.GetCountryOperationCompleted == null)) {
                this.GetCountryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountryOperationCompleted);
            }
            this.InvokeAsync("GetCountry", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        State,
                        County,
                        zone,
                        city,
                        Mun}, this.GetCountryOperationCompleted, userState);
        }
        
        private void OnGetCountryOperationCompleted(object arg) {
            if ((this.GetCountryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountryCompleted(this, new GetCountryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOfficeInf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfficesSelect GetOfficeInf(string _User, string _Pass, string MunName, string Mun, string Office) {
            object[] results = this.Invoke("GetOfficeInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        Mun,
                        Office});
            return ((OfficesSelect)(results[0]));
        }
        
        /// <remarks/>
        public void GetOfficeInfAsync(string _User, string _Pass, string MunName, string Mun, string Office) {
            this.GetOfficeInfAsync(_User, _Pass, MunName, Mun, Office, null);
        }
        
        /// <remarks/>
        public void GetOfficeInfAsync(string _User, string _Pass, string MunName, string Mun, string Office, object userState) {
            if ((this.GetOfficeInfOperationCompleted == null)) {
                this.GetOfficeInfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOfficeInfOperationCompleted);
            }
            this.InvokeAsync("GetOfficeInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        Mun,
                        Office}, this.GetOfficeInfOperationCompleted, userState);
        }
        
        private void OnGetOfficeInfOperationCompleted(object arg) {
            if ((this.GetOfficeInfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOfficeInfCompleted(this, new GetOfficeInfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMunInf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MunicipalitySelect GetMunInf(string _User, string _Pass, string MunName, string Mun) {
            object[] results = this.Invoke("GetMunInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        Mun});
            return ((MunicipalitySelect)(results[0]));
        }
        
        /// <remarks/>
        public void GetMunInfAsync(string _User, string _Pass, string MunName, string Mun) {
            this.GetMunInfAsync(_User, _Pass, MunName, Mun, null);
        }
        
        /// <remarks/>
        public void GetMunInfAsync(string _User, string _Pass, string MunName, string Mun, object userState) {
            if ((this.GetMunInfOperationCompleted == null)) {
                this.GetMunInfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMunInfOperationCompleted);
            }
            this.InvokeAsync("GetMunInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        Mun}, this.GetMunInfOperationCompleted, userState);
        }
        
        private void OnGetMunInfOperationCompleted(object arg) {
            if ((this.GetMunInfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMunInfCompleted(this, new GetMunInfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLocalInf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LocalSelect GetLocalInf(string _User, string _Pass, string MunName, string Mun, string Local) {
            object[] results = this.Invoke("GetLocalInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        Mun,
                        Local});
            return ((LocalSelect)(results[0]));
        }
        
        /// <remarks/>
        public void GetLocalInfAsync(string _User, string _Pass, string MunName, string Mun, string Local) {
            this.GetLocalInfAsync(_User, _Pass, MunName, Mun, Local, null);
        }
        
        /// <remarks/>
        public void GetLocalInfAsync(string _User, string _Pass, string MunName, string Mun, string Local, object userState) {
            if ((this.GetLocalInfOperationCompleted == null)) {
                this.GetLocalInfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocalInfOperationCompleted);
            }
            this.InvokeAsync("GetLocalInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        Mun,
                        Local}, this.GetLocalInfOperationCompleted, userState);
        }
        
        private void OnGetLocalInfOperationCompleted(object arg) {
            if ((this.GetLocalInfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocalInfCompleted(this, new GetLocalInfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarClassInf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CarClassSelect GetCarClassInf(string _User, string _Pass, string MunName, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass) {
            object[] results = this.Invoke("GetCarClassInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        CarMakeType,
                        CarAccountType,
                        CarCabin,
                        CarSystem,
                        CarTip,
                        CarClass});
            return ((CarClassSelect)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarClassInfAsync(string _User, string _Pass, string MunName, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass) {
            this.GetCarClassInfAsync(_User, _Pass, MunName, CarMakeType, CarAccountType, CarCabin, CarSystem, CarTip, CarClass, null);
        }
        
        /// <remarks/>
        public void GetCarClassInfAsync(string _User, string _Pass, string MunName, string CarMakeType, string CarAccountType, string CarCabin, string CarSystem, string CarTip, string CarClass, object userState) {
            if ((this.GetCarClassInfOperationCompleted == null)) {
                this.GetCarClassInfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarClassInfOperationCompleted);
            }
            this.InvokeAsync("GetCarClassInf", new object[] {
                        _User,
                        _Pass,
                        MunName,
                        CarMakeType,
                        CarAccountType,
                        CarCabin,
                        CarSystem,
                        CarTip,
                        CarClass}, this.GetCarClassInfOperationCompleted, userState);
        }
        
        private void OnGetCarClassInfOperationCompleted(object arg) {
            if ((this.GetCarClassInfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarClassInfCompleted(this, new GetCarClassInfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRateForWebService {
        
        private string fldNameField;
        
        private System.Nullable<int> fldYearField;
        
        private System.Nullable<int> fldFromModelField;
        
        private System.Nullable<int> fldToModelField;
        
        private System.Nullable<int> fldPriceField;
        
        private System.Nullable<int> fldFromCylinderField;
        
        private System.Nullable<int> fldToCylinderField;
        
        private System.Nullable<int> fldFromWheelField;
        
        private System.Nullable<int> fldToWheelField;
        
        private System.Nullable<int> fldFromContentMotorField;
        
        private System.Nullable<int> fldToContentMotorField;
        
        /// <remarks/>
        public string fldName {
            get {
                return this.fldNameField;
            }
            set {
                this.fldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldYear {
            get {
                return this.fldYearField;
            }
            set {
                this.fldYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldFromModel {
            get {
                return this.fldFromModelField;
            }
            set {
                this.fldFromModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldToModel {
            get {
                return this.fldToModelField;
            }
            set {
                this.fldToModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldPrice {
            get {
                return this.fldPriceField;
            }
            set {
                this.fldPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldFromCylinder {
            get {
                return this.fldFromCylinderField;
            }
            set {
                this.fldFromCylinderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldToCylinder {
            get {
                return this.fldToCylinderField;
            }
            set {
                this.fldToCylinderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldFromWheel {
            get {
                return this.fldFromWheelField;
            }
            set {
                this.fldFromWheelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldToWheel {
            get {
                return this.fldToWheelField;
            }
            set {
                this.fldToWheelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldFromContentMotor {
            get {
                return this.fldFromContentMotorField;
            }
            set {
                this.fldFromContentMotorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldToContentMotor {
            get {
                return this.fldToContentMotorField;
            }
            set {
                this.fldToContentMotorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CarClassSelect {
        
        private int fldIDField;
        
        private string fldNameField;
        
        private string fldCarModelNameField;
        
        private int fldCarModelIDField;
        
        private long fldUserIDField;
        
        private string fldDescField;
        
        private string fldDateField;
        
        private string fldUserNameField;
        
        private int fldCarPatternModelIDField;
        
        private System.Nullable<byte> fldCylinderNumberField;
        
        private System.Nullable<byte> fldWheelNumberField;
        
        private System.Nullable<byte> fldPivotNumberField;
        
        private System.Nullable<int> fldContentMotorField;
        
        private string fldFuelTypeNameField;
        
        private System.Nullable<int> fldFuelTypeIDField;
        
        private string fldCarPatternModelNameField;
        
        /// <remarks/>
        public int fldID {
            get {
                return this.fldIDField;
            }
            set {
                this.fldIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldName {
            get {
                return this.fldNameField;
            }
            set {
                this.fldNameField = value;
            }
        }
        
        /// <remarks/>
        public string fldCarModelName {
            get {
                return this.fldCarModelNameField;
            }
            set {
                this.fldCarModelNameField = value;
            }
        }
        
        /// <remarks/>
        public int fldCarModelID {
            get {
                return this.fldCarModelIDField;
            }
            set {
                this.fldCarModelIDField = value;
            }
        }
        
        /// <remarks/>
        public long fldUserID {
            get {
                return this.fldUserIDField;
            }
            set {
                this.fldUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldDesc {
            get {
                return this.fldDescField;
            }
            set {
                this.fldDescField = value;
            }
        }
        
        /// <remarks/>
        public string fldDate {
            get {
                return this.fldDateField;
            }
            set {
                this.fldDateField = value;
            }
        }
        
        /// <remarks/>
        public string fldUserName {
            get {
                return this.fldUserNameField;
            }
            set {
                this.fldUserNameField = value;
            }
        }
        
        /// <remarks/>
        public int fldCarPatternModelID {
            get {
                return this.fldCarPatternModelIDField;
            }
            set {
                this.fldCarPatternModelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> fldCylinderNumber {
            get {
                return this.fldCylinderNumberField;
            }
            set {
                this.fldCylinderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> fldWheelNumber {
            get {
                return this.fldWheelNumberField;
            }
            set {
                this.fldWheelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> fldPivotNumber {
            get {
                return this.fldPivotNumberField;
            }
            set {
                this.fldPivotNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldContentMotor {
            get {
                return this.fldContentMotorField;
            }
            set {
                this.fldContentMotorField = value;
            }
        }
        
        /// <remarks/>
        public string fldFuelTypeName {
            get {
                return this.fldFuelTypeNameField;
            }
            set {
                this.fldFuelTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldFuelTypeID {
            get {
                return this.fldFuelTypeIDField;
            }
            set {
                this.fldFuelTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldCarPatternModelName {
            get {
                return this.fldCarPatternModelNameField;
            }
            set {
                this.fldCarPatternModelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LocalSelect {
        
        private long fldIDField;
        
        private string fldNameField;
        
        private string fldMunicipalityNameField;
        
        private int fldMunicipalityIDField;
        
        private long fldUserIDField;
        
        private string fldDescField;
        
        private string fldDateField;
        
        private string fldUserNameField;
        
        private string fldServiceCodeField;
        
        private string fldSourceInformaticsField;
        
        /// <remarks/>
        public long fldID {
            get {
                return this.fldIDField;
            }
            set {
                this.fldIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldName {
            get {
                return this.fldNameField;
            }
            set {
                this.fldNameField = value;
            }
        }
        
        /// <remarks/>
        public string fldMunicipalityName {
            get {
                return this.fldMunicipalityNameField;
            }
            set {
                this.fldMunicipalityNameField = value;
            }
        }
        
        /// <remarks/>
        public int fldMunicipalityID {
            get {
                return this.fldMunicipalityIDField;
            }
            set {
                this.fldMunicipalityIDField = value;
            }
        }
        
        /// <remarks/>
        public long fldUserID {
            get {
                return this.fldUserIDField;
            }
            set {
                this.fldUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldDesc {
            get {
                return this.fldDescField;
            }
            set {
                this.fldDescField = value;
            }
        }
        
        /// <remarks/>
        public string fldDate {
            get {
                return this.fldDateField;
            }
            set {
                this.fldDateField = value;
            }
        }
        
        /// <remarks/>
        public string fldUserName {
            get {
                return this.fldUserNameField;
            }
            set {
                this.fldUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string fldServiceCode {
            get {
                return this.fldServiceCodeField;
            }
            set {
                this.fldServiceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string fldSourceInformatics {
            get {
                return this.fldSourceInformaticsField;
            }
            set {
                this.fldSourceInformaticsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MunicipalitySelect {
        
        private int fldIDField;
        
        private string fldNameField;
        
        private string fldCityNameField;
        
        private int fldCityIDField;
        
        private string fldInformaticesCodeField;
        
        private byte fldServiceCodeField;
        
        private string fldRWUserNameField;
        
        private string fldRWPassField;
        
        private long fldUserIDField;
        
        private string fldDescField;
        
        private string fldDateField;
        
        private string fldUserNameField;
        
        /// <remarks/>
        public int fldID {
            get {
                return this.fldIDField;
            }
            set {
                this.fldIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldName {
            get {
                return this.fldNameField;
            }
            set {
                this.fldNameField = value;
            }
        }
        
        /// <remarks/>
        public string fldCityName {
            get {
                return this.fldCityNameField;
            }
            set {
                this.fldCityNameField = value;
            }
        }
        
        /// <remarks/>
        public int fldCityID {
            get {
                return this.fldCityIDField;
            }
            set {
                this.fldCityIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldInformaticesCode {
            get {
                return this.fldInformaticesCodeField;
            }
            set {
                this.fldInformaticesCodeField = value;
            }
        }
        
        /// <remarks/>
        public byte fldServiceCode {
            get {
                return this.fldServiceCodeField;
            }
            set {
                this.fldServiceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string fldRWUserName {
            get {
                return this.fldRWUserNameField;
            }
            set {
                this.fldRWUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string fldRWPass {
            get {
                return this.fldRWPassField;
            }
            set {
                this.fldRWPassField = value;
            }
        }
        
        /// <remarks/>
        public long fldUserID {
            get {
                return this.fldUserIDField;
            }
            set {
                this.fldUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldDesc {
            get {
                return this.fldDescField;
            }
            set {
                this.fldDescField = value;
            }
        }
        
        /// <remarks/>
        public string fldDate {
            get {
                return this.fldDateField;
            }
            set {
                this.fldDateField = value;
            }
        }
        
        /// <remarks/>
        public string fldUserName {
            get {
                return this.fldUserNameField;
            }
            set {
                this.fldUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficesSelect {
        
        private long fldIDField;
        
        private string fldNameField;
        
        private string fldAddressField;
        
        private string fldOfficesTypeField;
        
        private byte fldOfficesTypeIDField;
        
        private string fldMunicipalityNameField;
        
        private System.Nullable<int> fldMunicipalityIDField;
        
        private string fldLocalNameField;
        
        private System.Nullable<long> fldLocalIDField;
        
        private string fldAreaNameField;
        
        private System.Nullable<long> fldAreaIDField;
        
        private long fldUserIDField;
        
        private string fldDescField;
        
        private string fldDateField;
        
        private string fldTelField;
        
        private string fldUserNameField;
        
        /// <remarks/>
        public long fldID {
            get {
                return this.fldIDField;
            }
            set {
                this.fldIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldName {
            get {
                return this.fldNameField;
            }
            set {
                this.fldNameField = value;
            }
        }
        
        /// <remarks/>
        public string fldAddress {
            get {
                return this.fldAddressField;
            }
            set {
                this.fldAddressField = value;
            }
        }
        
        /// <remarks/>
        public string fldOfficesType {
            get {
                return this.fldOfficesTypeField;
            }
            set {
                this.fldOfficesTypeField = value;
            }
        }
        
        /// <remarks/>
        public byte fldOfficesTypeID {
            get {
                return this.fldOfficesTypeIDField;
            }
            set {
                this.fldOfficesTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldMunicipalityName {
            get {
                return this.fldMunicipalityNameField;
            }
            set {
                this.fldMunicipalityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldMunicipalityID {
            get {
                return this.fldMunicipalityIDField;
            }
            set {
                this.fldMunicipalityIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldLocalName {
            get {
                return this.fldLocalNameField;
            }
            set {
                this.fldLocalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> fldLocalID {
            get {
                return this.fldLocalIDField;
            }
            set {
                this.fldLocalIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldAreaName {
            get {
                return this.fldAreaNameField;
            }
            set {
                this.fldAreaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> fldAreaID {
            get {
                return this.fldAreaIDField;
            }
            set {
                this.fldAreaIDField = value;
            }
        }
        
        /// <remarks/>
        public long fldUserID {
            get {
                return this.fldUserIDField;
            }
            set {
                this.fldUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldDesc {
            get {
                return this.fldDescField;
            }
            set {
                this.fldDescField = value;
            }
        }
        
        /// <remarks/>
        public string fldDate {
            get {
                return this.fldDateField;
            }
            set {
                this.fldDateField = value;
            }
        }
        
        /// <remarks/>
        public string fldTel {
            get {
                return this.fldTelField;
            }
            set {
                this.fldTelField = value;
            }
        }
        
        /// <remarks/>
        public string fldUserName {
            get {
                return this.fldUserNameField;
            }
            set {
                this.fldUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryDivForWebService {
        
        private System.Nullable<int> fldIDField;
        
        private string fldNodeNameField;
        
        private System.Nullable<byte> fldNodeTypeField;
        
        private System.Nullable<int> fldPIDField;
        
        private string fldPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldID {
            get {
                return this.fldIDField;
            }
            set {
                this.fldIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldNodeName {
            get {
                return this.fldNodeNameField;
            }
            set {
                this.fldNodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> fldNodeType {
            get {
                return this.fldNodeTypeField;
            }
            set {
                this.fldNodeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fldPID {
            get {
                return this.fldPIDField;
            }
            set {
                this.fldPIDField = value;
            }
        }
        
        /// <remarks/>
        public string fldPath {
            get {
                return this.fldPathField;
            }
            set {
                this.fldPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClassForWebService {
        
        private string classNameField;
        
        /// <remarks/>
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckAccountChargeCompletedEventHandler(object sender, CheckAccountChargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckAccountChargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckAccountChargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetRateCompletedEventHandler(object sender, GetRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRateForWebService[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRateForWebService[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetClassCompletedEventHandler(object sender, GetClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetClassForWebService[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetClassForWebService[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCountryCompletedEventHandler(object sender, GetCountryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetCountryDivForWebService[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetCountryDivForWebService[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetOfficeInfCompletedEventHandler(object sender, GetOfficeInfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOfficeInfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOfficeInfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfficesSelect Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfficesSelect)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMunInfCompletedEventHandler(object sender, GetMunInfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMunInfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMunInfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MunicipalitySelect Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MunicipalitySelect)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetLocalInfCompletedEventHandler(object sender, GetLocalInfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocalInfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocalInfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LocalSelect Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LocalSelect)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCarClassInfCompletedEventHandler(object sender, GetCarClassInfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarClassInfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarClassInfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CarClassSelect Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CarClassSelect)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591