//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cartaxtest2Entities : DbContext
    {
        public cartaxtest2Entities()
            : base("name=cartaxtest2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<prs_tblTarfGharardadSelect> prs_tblTarfGharardadSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblTarfGharardadSelect>("prs_tblTarfGharardadSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<prs_User_GharardadSelect> prs_User_GharardadSelect(string fieldname, string value, Nullable<int> h, string pass, Nullable<int> fldUserId, string fldUserPass)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(int));
    
            var fldUserPassParameter = fldUserPass != null ?
                new ObjectParameter("fldUserPass", fldUserPass) :
                new ObjectParameter("fldUserPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_User_GharardadSelect>("prs_User_GharardadSelect", fieldnameParameter, valueParameter, hParameter, passParameter, fldUserIdParameter, fldUserPassParameter);
        }
    
        public virtual int prs_tblShakhsHaghighi_HoghoghiDelete(Nullable<long> fldId, Nullable<long> fldUserId, string fldUserPass)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            var fldUserPassParameter = fldUserPass != null ?
                new ObjectParameter("fldUserPass", fldUserPass) :
                new ObjectParameter("fldUserPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblShakhsHaghighi_HoghoghiDelete", fldIdParameter, fldUserIdParameter, fldUserPassParameter);
        }
    
        public virtual int prs_tblShakhsHaghighi_HoghoghiInsert(string fldName, string fldFamily, string fldNationalCode, string fldCodeEghtesadi, Nullable<byte> fldTypeShakhsId, string fldCodePosti, string fldCodeShobe, Nullable<long> fldOwnerId, Nullable<long> fldUserID, string fldDesc)
        {
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldFamilyParameter = fldFamily != null ?
                new ObjectParameter("fldFamily", fldFamily) :
                new ObjectParameter("fldFamily", typeof(string));
    
            var fldNationalCodeParameter = fldNationalCode != null ?
                new ObjectParameter("fldNationalCode", fldNationalCode) :
                new ObjectParameter("fldNationalCode", typeof(string));
    
            var fldCodeEghtesadiParameter = fldCodeEghtesadi != null ?
                new ObjectParameter("fldCodeEghtesadi", fldCodeEghtesadi) :
                new ObjectParameter("fldCodeEghtesadi", typeof(string));
    
            var fldTypeShakhsIdParameter = fldTypeShakhsId.HasValue ?
                new ObjectParameter("fldTypeShakhsId", fldTypeShakhsId) :
                new ObjectParameter("fldTypeShakhsId", typeof(byte));
    
            var fldCodePostiParameter = fldCodePosti != null ?
                new ObjectParameter("fldCodePosti", fldCodePosti) :
                new ObjectParameter("fldCodePosti", typeof(string));
    
            var fldCodeShobeParameter = fldCodeShobe != null ?
                new ObjectParameter("fldCodeShobe", fldCodeShobe) :
                new ObjectParameter("fldCodeShobe", typeof(string));
    
            var fldOwnerIdParameter = fldOwnerId.HasValue ?
                new ObjectParameter("fldOwnerId", fldOwnerId) :
                new ObjectParameter("fldOwnerId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblShakhsHaghighi_HoghoghiInsert", fldNameParameter, fldFamilyParameter, fldNationalCodeParameter, fldCodeEghtesadiParameter, fldTypeShakhsIdParameter, fldCodePostiParameter, fldCodeShobeParameter, fldOwnerIdParameter, fldUserIDParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<prs_tblShakhsHaghighi_HoghoghiSelect> prs_tblShakhsHaghighi_HoghoghiSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblShakhsHaghighi_HoghoghiSelect>("prs_tblShakhsHaghighi_HoghoghiSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_tblShakhsHaghighi_HoghoghiUpdate(Nullable<long> fldId, string fldName, string fldFamily, string fldNationalCode, string fldCodeEghtesadi, Nullable<byte> fldTypeShakhsId, string fldCodePosti, string fldCodeShobe, Nullable<long> fldOwnerId, Nullable<long> fldUserID, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var fldNameParameter = fldName != null ?
                new ObjectParameter("fldName", fldName) :
                new ObjectParameter("fldName", typeof(string));
    
            var fldFamilyParameter = fldFamily != null ?
                new ObjectParameter("fldFamily", fldFamily) :
                new ObjectParameter("fldFamily", typeof(string));
    
            var fldNationalCodeParameter = fldNationalCode != null ?
                new ObjectParameter("fldNationalCode", fldNationalCode) :
                new ObjectParameter("fldNationalCode", typeof(string));
    
            var fldCodeEghtesadiParameter = fldCodeEghtesadi != null ?
                new ObjectParameter("fldCodeEghtesadi", fldCodeEghtesadi) :
                new ObjectParameter("fldCodeEghtesadi", typeof(string));
    
            var fldTypeShakhsIdParameter = fldTypeShakhsId.HasValue ?
                new ObjectParameter("fldTypeShakhsId", fldTypeShakhsId) :
                new ObjectParameter("fldTypeShakhsId", typeof(byte));
    
            var fldCodePostiParameter = fldCodePosti != null ?
                new ObjectParameter("fldCodePosti", fldCodePosti) :
                new ObjectParameter("fldCodePosti", typeof(string));
    
            var fldCodeShobeParameter = fldCodeShobe != null ?
                new ObjectParameter("fldCodeShobe", fldCodeShobe) :
                new ObjectParameter("fldCodeShobe", typeof(string));
    
            var fldOwnerIdParameter = fldOwnerId.HasValue ?
                new ObjectParameter("fldOwnerId", fldOwnerId) :
                new ObjectParameter("fldOwnerId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblShakhsHaghighi_HoghoghiUpdate", fldIdParameter, fldNameParameter, fldFamilyParameter, fldNationalCodeParameter, fldCodeEghtesadiParameter, fldTypeShakhsIdParameter, fldCodePostiParameter, fldCodeShobeParameter, fldOwnerIdParameter, fldUserIDParameter, fldDescParameter);
        }
    
        public virtual int prs_tblTarfGharardadDelete(Nullable<int> fldId, Nullable<long> fldUserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblTarfGharardadDelete", fldIdParameter, fldUserIdParameter);
        }
    
        public virtual int prs_tblTarfGharardadInsert(ObjectParameter fldId, Nullable<long> fldShakhsId, string fldUniqId, byte[] fldPrivateKey, byte[] fldSignatureCertificate, Nullable<long> fldUserID, string fldDesc)
        {
            var fldShakhsIdParameter = fldShakhsId.HasValue ?
                new ObjectParameter("fldShakhsId", fldShakhsId) :
                new ObjectParameter("fldShakhsId", typeof(long));
    
            var fldUniqIdParameter = fldUniqId != null ?
                new ObjectParameter("fldUniqId", fldUniqId) :
                new ObjectParameter("fldUniqId", typeof(string));
    
            var fldPrivateKeyParameter = fldPrivateKey != null ?
                new ObjectParameter("fldPrivateKey", fldPrivateKey) :
                new ObjectParameter("fldPrivateKey", typeof(byte[]));
    
            var fldSignatureCertificateParameter = fldSignatureCertificate != null ?
                new ObjectParameter("fldSignatureCertificate", fldSignatureCertificate) :
                new ObjectParameter("fldSignatureCertificate", typeof(byte[]));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblTarfGharardadInsert", fldId, fldShakhsIdParameter, fldUniqIdParameter, fldPrivateKeyParameter, fldSignatureCertificateParameter, fldUserIDParameter, fldDescParameter);
        }
    
        public virtual int prs_tblTarfGharardadUpdate(Nullable<int> fldId, Nullable<long> fldShakhsId, string fldUniqId, byte[] fldPrivateKey, byte[] fldSignatureCertificate, Nullable<long> fldUserID, string fldDesc)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(int));
    
            var fldShakhsIdParameter = fldShakhsId.HasValue ?
                new ObjectParameter("fldShakhsId", fldShakhsId) :
                new ObjectParameter("fldShakhsId", typeof(long));
    
            var fldUniqIdParameter = fldUniqId != null ?
                new ObjectParameter("fldUniqId", fldUniqId) :
                new ObjectParameter("fldUniqId", typeof(string));
    
            var fldPrivateKeyParameter = fldPrivateKey != null ?
                new ObjectParameter("fldPrivateKey", fldPrivateKey) :
                new ObjectParameter("fldPrivateKey", typeof(byte[]));
    
            var fldSignatureCertificateParameter = fldSignatureCertificate != null ?
                new ObjectParameter("fldSignatureCertificate", fldSignatureCertificate) :
                new ObjectParameter("fldSignatureCertificate", typeof(byte[]));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblTarfGharardadUpdate", fldIdParameter, fldShakhsIdParameter, fldUniqIdParameter, fldPrivateKeyParameter, fldSignatureCertificateParameter, fldUserIDParameter, fldDescParameter);
        }
    
        public virtual ObjectResult<prs_tblTypeShakhsSelect> prs_tblTypeShakhsSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblTypeShakhsSelect>("prs_tblTypeShakhsSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_User_GharardadInsert(ObjectParameter fldId, Nullable<int> fldTarfGharardadId, Nullable<bool> fldStatus, string fldPassword, string fldUserName, Nullable<long> fldUserID, string fldDesc, byte[] fldImage)
        {
            var fldTarfGharardadIdParameter = fldTarfGharardadId.HasValue ?
                new ObjectParameter("fldTarfGharardadId", fldTarfGharardadId) :
                new ObjectParameter("fldTarfGharardadId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(bool));
    
            var fldPasswordParameter = fldPassword != null ?
                new ObjectParameter("fldPassword", fldPassword) :
                new ObjectParameter("fldPassword", typeof(string));
    
            var fldUserNameParameter = fldUserName != null ?
                new ObjectParameter("fldUserName", fldUserName) :
                new ObjectParameter("fldUserName", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldImageParameter = fldImage != null ?
                new ObjectParameter("fldImage", fldImage) :
                new ObjectParameter("fldImage", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_User_GharardadInsert", fldId, fldTarfGharardadIdParameter, fldStatusParameter, fldPasswordParameter, fldUserNameParameter, fldUserIDParameter, fldDescParameter, fldImageParameter);
        }
    
        public virtual int prs_User_GharardadUpdate(Nullable<long> fldID, Nullable<int> fldTarfGharardadId, Nullable<bool> fldStatus, string fldUserName, Nullable<long> fldUserID, string fldDesc, byte[] fldpic)
        {
            var fldIDParameter = fldID.HasValue ?
                new ObjectParameter("fldID", fldID) :
                new ObjectParameter("fldID", typeof(long));
    
            var fldTarfGharardadIdParameter = fldTarfGharardadId.HasValue ?
                new ObjectParameter("fldTarfGharardadId", fldTarfGharardadId) :
                new ObjectParameter("fldTarfGharardadId", typeof(int));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(bool));
    
            var fldUserNameParameter = fldUserName != null ?
                new ObjectParameter("fldUserName", fldUserName) :
                new ObjectParameter("fldUserName", typeof(string));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            var fldDescParameter = fldDesc != null ?
                new ObjectParameter("fldDesc", fldDesc) :
                new ObjectParameter("fldDesc", typeof(string));
    
            var fldpicParameter = fldpic != null ?
                new ObjectParameter("fldpic", fldpic) :
                new ObjectParameter("fldpic", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_User_GharardadUpdate", fldIDParameter, fldTarfGharardadIdParameter, fldStatusParameter, fldUserNameParameter, fldUserIDParameter, fldDescParameter, fldpicParameter);
        }
    
        public virtual ObjectResult<prs_tblMeasureUnitSelect> prs_tblMeasureUnitSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblMeasureUnitSelect>("prs_tblMeasureUnitSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<prs_tblKala_KhedmatSelect> prs_tblKala_KhedmatSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblKala_KhedmatSelect>("prs_tblKala_KhedmatSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual ObjectResult<prs_SelectDetailSooratHesab> prs_SelectDetailSooratHesab(Nullable<int> fldIdSooratHesab)
        {
            var fldIdSooratHesabParameter = fldIdSooratHesab.HasValue ?
                new ObjectParameter("fldIdSooratHesab", fldIdSooratHesab) :
                new ObjectParameter("fldIdSooratHesab", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_SelectDetailSooratHesab>("prs_SelectDetailSooratHesab", fldIdSooratHesabParameter);
        }
    
        public virtual ObjectResult<prs_SelectHeaderSooratHesab> prs_SelectHeaderSooratHesab(Nullable<int> fldIdSooratHesab)
        {
            var fldIdSooratHesabParameter = fldIdSooratHesab.HasValue ?
                new ObjectParameter("fldIdSooratHesab", fldIdSooratHesab) :
                new ObjectParameter("fldIdSooratHesab", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_SelectHeaderSooratHesab>("prs_SelectHeaderSooratHesab", fldIdSooratHesabParameter);
        }
    
        public virtual int prs_tblSooratHesabHeader_ValueInsert(Nullable<long> fldHeaderId, string fldValue, Nullable<short> fldParametrHeaderId, Nullable<long> fldUserId)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldValueParameter = fldValue != null ?
                new ObjectParameter("fldValue", fldValue) :
                new ObjectParameter("fldValue", typeof(string));
    
            var fldParametrHeaderIdParameter = fldParametrHeaderId.HasValue ?
                new ObjectParameter("fldParametrHeaderId", fldParametrHeaderId) :
                new ObjectParameter("fldParametrHeaderId", typeof(short));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabHeader_ValueInsert", fldHeaderIdParameter, fldValueParameter, fldParametrHeaderIdParameter, fldUserIdParameter);
        }
    
        public virtual ObjectResult<prs_tblCurrencyTypeSelect> prs_tblCurrencyTypeSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblCurrencyTypeSelect>("prs_tblCurrencyTypeSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_tblSooratHesab_DetailInsert(Nullable<long> fldHeaderId, Nullable<long> fldUserID)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldUserIDParameter = fldUserID.HasValue ?
                new ObjectParameter("fldUserID", fldUserID) :
                new ObjectParameter("fldUserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_DetailInsert", fldHeaderIdParameter, fldUserIDParameter);
        }
    
        public virtual int prs_tblSooratHesab_HeaderInsert(ObjectParameter fldid, string fldTaxId, Nullable<System.DateTime> fldIndatim, Nullable<System.DateTime> fldIndati2m, Nullable<byte> fldInty, Nullable<byte> fldInp, string fldInno, string fldIrtaxId, Nullable<long> fldKharidarId, Nullable<long> fldForooshandeId, Nullable<long> fldUserId)
        {
            var fldTaxIdParameter = fldTaxId != null ?
                new ObjectParameter("fldTaxId", fldTaxId) :
                new ObjectParameter("fldTaxId", typeof(string));
    
            var fldIndatimParameter = fldIndatim.HasValue ?
                new ObjectParameter("fldIndatim", fldIndatim) :
                new ObjectParameter("fldIndatim", typeof(System.DateTime));
    
            var fldIndati2mParameter = fldIndati2m.HasValue ?
                new ObjectParameter("fldIndati2m", fldIndati2m) :
                new ObjectParameter("fldIndati2m", typeof(System.DateTime));
    
            var fldIntyParameter = fldInty.HasValue ?
                new ObjectParameter("fldInty", fldInty) :
                new ObjectParameter("fldInty", typeof(byte));
    
            var fldInpParameter = fldInp.HasValue ?
                new ObjectParameter("fldInp", fldInp) :
                new ObjectParameter("fldInp", typeof(byte));
    
            var fldInnoParameter = fldInno != null ?
                new ObjectParameter("fldInno", fldInno) :
                new ObjectParameter("fldInno", typeof(string));
    
            var fldIrtaxIdParameter = fldIrtaxId != null ?
                new ObjectParameter("fldIrtaxId", fldIrtaxId) :
                new ObjectParameter("fldIrtaxId", typeof(string));
    
            var fldKharidarIdParameter = fldKharidarId.HasValue ?
                new ObjectParameter("fldKharidarId", fldKharidarId) :
                new ObjectParameter("fldKharidarId", typeof(long));
    
            var fldForooshandeIdParameter = fldForooshandeId.HasValue ?
                new ObjectParameter("fldForooshandeId", fldForooshandeId) :
                new ObjectParameter("fldForooshandeId", typeof(long));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_HeaderInsert", fldid, fldTaxIdParameter, fldIndatimParameter, fldIndati2mParameter, fldIntyParameter, fldInpParameter, fldInnoParameter, fldIrtaxIdParameter, fldKharidarIdParameter, fldForooshandeIdParameter, fldUserIdParameter);
        }
    
        public virtual ObjectResult<prs_tblSooratHesab_HeaderSelect> prs_tblSooratHesab_HeaderSelect(string fieldname, string value, Nullable<int> h)
        {
            var fieldnameParameter = fieldname != null ?
                new ObjectParameter("fieldname", fieldname) :
                new ObjectParameter("fieldname", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var hParameter = h.HasValue ?
                new ObjectParameter("h", h) :
                new ObjectParameter("h", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prs_tblSooratHesab_HeaderSelect>("prs_tblSooratHesab_HeaderSelect", fieldnameParameter, valueParameter, hParameter);
        }
    
        public virtual int prs_tblSooratHesab_HeaderDelete(Nullable<long> fldId, Nullable<long> flduserId)
        {
            var fldIdParameter = fldId.HasValue ?
                new ObjectParameter("fldId", fldId) :
                new ObjectParameter("fldId", typeof(long));
    
            var flduserIdParameter = flduserId.HasValue ?
                new ObjectParameter("flduserId", flduserId) :
                new ObjectParameter("flduserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesab_HeaderDelete", fldIdParameter, flduserIdParameter);
        }
    
        public virtual int prs_tblSooratHesabStatusInsert(Nullable<long> fldHeaderId, Nullable<byte> fldStatus, string fldMatn, string fldReferenceNumber, string fldUID, Nullable<long> fldUserId)
        {
            var fldHeaderIdParameter = fldHeaderId.HasValue ?
                new ObjectParameter("fldHeaderId", fldHeaderId) :
                new ObjectParameter("fldHeaderId", typeof(long));
    
            var fldStatusParameter = fldStatus.HasValue ?
                new ObjectParameter("fldStatus", fldStatus) :
                new ObjectParameter("fldStatus", typeof(byte));
    
            var fldMatnParameter = fldMatn != null ?
                new ObjectParameter("fldMatn", fldMatn) :
                new ObjectParameter("fldMatn", typeof(string));
    
            var fldReferenceNumberParameter = fldReferenceNumber != null ?
                new ObjectParameter("fldReferenceNumber", fldReferenceNumber) :
                new ObjectParameter("fldReferenceNumber", typeof(string));
    
            var fldUIDParameter = fldUID != null ?
                new ObjectParameter("fldUID", fldUID) :
                new ObjectParameter("fldUID", typeof(string));
    
            var fldUserIdParameter = fldUserId.HasValue ?
                new ObjectParameter("fldUserId", fldUserId) :
                new ObjectParameter("fldUserId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prs_tblSooratHesabStatusInsert", fldHeaderIdParameter, fldStatusParameter, fldMatnParameter, fldReferenceNumberParameter, fldUIDParameter, fldUserIdParameter);
        }
    }
}
