//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_AccountBankSelect
    {
        public int fldID { get; set; }
        public string fldAccountNumber { get; set; }
        public string fldBranchName { get; set; }
        public int fldBranchID { get; set; }
        public string fldCountryDivisionsName { get; set; }
        public long fldCountryDivisionsID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldBankName { get; set; }
        public int fldBankID { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryType { get; set; }
    }
}
