//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_BankSelect
    {
        public int fldID { get; set; }
        public string fldName { get; set; }
        public string fldType { get; set; }
        public int fldBankTypeID { get; set; }
        public byte fldCentralBankCode { get; set; }
        public string fldInfinitiveBank { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
    }
}
