//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_CarPlaqueSelect
    {
        public int fldID { get; set; }
        public string fldPlaqueNumber { get; set; }
        public int fldPlaqueCityID { get; set; }
        public int fldPlaqueSerialID { get; set; }
        public int fldPlaqueTypeID { get; set; }
        public long fldOwnerID { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldPlaqueCityName { get; set; }
        public string fldPlaqueTypeName { get; set; }
        public string fldPlaqueSerial { get; set; }
        public string fldOwnerName { get; set; }
        public string fldOwnerMelli_EconomicCode { get; set; }
        public string fldName { get; set; }
        public int fldStatusPlaqeID { get; set; }
        public string fldStatusPlaqeName { get; set; }
        public Nullable<int> fldCharacterPersianPlaqueID { get; set; }
        public Nullable<int> IsAccept { get; set; }
    }
}
