//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_Discount_LogSelect
    {
        public int fldID { get; set; }
        public string نام { get; set; }
        public System.DateTime تاریخ_شروع { get; set; }
        public System.DateTime تاریخ_پایان { get; set; }
        public bool نرخ_عوارض { get; set; }
        public bool قانون_جریمه { get; set; }
        public bool تبصره_ب_ماده_43 { get; set; }
        public bool سایر { get; set; }
        public int درصد_تخفیف { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public Nullable<System.DateTime> تاریخ_موثر { get; set; }
        public Nullable<bool> موثر_بر_کاربر { get; set; }
        public Nullable<bool> موثر_بر_دفاتر { get; set; }
        public Nullable<bool> موثر_بر_شهرداری { get; set; }
        public string تقسیمات_کشوری { get; set; }
        public string کاربرایجادکننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
