//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_SelectNameBankAndMunForBankInformation
    {
        public string fldBankName { get; set; }
        public int BankId { get; set; }
        public string fldMunName { get; set; }
        public Nullable<int> fldMunId { get; set; }
        public Nullable<long> fldCountryDiv { get; set; }
        public Nullable<int> fldLocalID { get; set; }
    }
}
