//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_SelectFullCarForSetMony
    {
        public string fldCarMakeName { get; set; }
        public int fldCarMakeID { get; set; }
        public string fldCarAccountName { get; set; }
        public int fldCarAccountID { get; set; }
        public string fldCarCabinName { get; set; }
        public int fldCarCabinID { get; set; }
        public string fldCarSystemName { get; set; }
        public int fldCarSystemID { get; set; }
        public string fldCarModelName { get; set; }
        public int fldCarModelID { get; set; }
        public string fldCarClassName { get; set; }
        public int fldCarClassID { get; set; }
        public Nullable<int> fldPrice { get; set; }
        public string fldPrice_S { get; set; }
    }
}
