//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_tblOfficeReciptNerkhSelect
    {
        public Nullable<int> fldID { get; set; }
        public Nullable<int> fldCountryDivId { get; set; }
        public Nullable<int> fldCarSeriesId { get; set; }
        public Nullable<int> fldPrice { get; set; }
        public string fldAzTarikh { get; set; }
        public Nullable<int> fldServiceId { get; set; }
    }
}
