//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_WebTransactionSelect
    {
        public int fldId { get; set; }
        public int fldMablagh { get; set; }
        public string fldCodeTarakonesh { get; set; }
        public string fldTarikh { get; set; }
        public string fldType { get; set; }
    }
}
