//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Avarez.epishkhan {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="dev.pishkhan.nwsv1SOAPBinding", Namespace="http://www.wso2.org/php")]
    public partial class devpishkhannwsv1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback serviceRefundOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback serviceCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback servicePayOperationCompleted;
        
        private System.Threading.SendOrPostCallback infoOperationCompleted;
        
        private System.Threading.SendOrPostCallback serviceCallOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public devpishkhannwsv1() {
            this.Url = global::Avarez.Properties.Settings.Default.Avarez_ir_epishkhan_dev_dev_pishkhan_nwsv1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event serviceRefundCompletedEventHandler serviceRefundCompleted;
        
        /// <remarks/>
        public event verifyCompletedEventHandler verifyCompleted;
        
        /// <remarks/>
        public event serviceCancelCompletedEventHandler serviceCancelCompleted;
        
        /// <remarks/>
        public event validateCompletedEventHandler validateCompleted;
        
        /// <remarks/>
        public event validateTokenCompletedEventHandler validateTokenCompleted;
        
        /// <remarks/>
        public event servicePayCompletedEventHandler servicePayCompleted;
        
        /// <remarks/>
        public event infoCompletedEventHandler infoCompleted;
        
        /// <remarks/>
        public event serviceCallCompletedEventHandler serviceCallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/serviceRefund", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("pkhref")]
        public int serviceRefund(string pass, int parent_pkhref, string parent_refnum, int parent_service_id, int amount) {
            object[] results = this.Invoke("serviceRefund", new object[] {
                        pass,
                        parent_pkhref,
                        parent_refnum,
                        parent_service_id,
                        amount});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void serviceRefundAsync(string pass, int parent_pkhref, string parent_refnum, int parent_service_id, int amount) {
            this.serviceRefundAsync(pass, parent_pkhref, parent_refnum, parent_service_id, amount, null);
        }
        
        /// <remarks/>
        public void serviceRefundAsync(string pass, int parent_pkhref, string parent_refnum, int parent_service_id, int amount, object userState) {
            if ((this.serviceRefundOperationCompleted == null)) {
                this.serviceRefundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviceRefundOperationCompleted);
            }
            this.InvokeAsync("serviceRefund", new object[] {
                        pass,
                        parent_pkhref,
                        parent_refnum,
                        parent_service_id,
                        amount}, this.serviceRefundOperationCompleted, userState);
        }
        
        private void OnserviceRefundOperationCompleted(object arg) {
            if ((this.serviceRefundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviceRefundCompleted(this, new serviceRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/verify", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("pkhref")]
        public int verify(string pass, int serial, string refnum) {
            object[] results = this.Invoke("verify", new object[] {
                        pass,
                        serial,
                        refnum});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void verifyAsync(string pass, int serial, string refnum) {
            this.verifyAsync(pass, serial, refnum, null);
        }
        
        /// <remarks/>
        public void verifyAsync(string pass, int serial, string refnum, object userState) {
            if ((this.verifyOperationCompleted == null)) {
                this.verifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyOperationCompleted);
            }
            this.InvokeAsync("verify", new object[] {
                        pass,
                        serial,
                        refnum}, this.verifyOperationCompleted, userState);
        }
        
        private void OnverifyOperationCompleted(object arg) {
            if ((this.verifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyCompleted(this, new verifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/serviceCancel", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("pkhref")]
        public int serviceCancel(string pass, int parent_pkhref, int parent_refnum, int parent_service_id) {
            object[] results = this.Invoke("serviceCancel", new object[] {
                        pass,
                        parent_pkhref,
                        parent_refnum,
                        parent_service_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void serviceCancelAsync(string pass, int parent_pkhref, int parent_refnum, int parent_service_id) {
            this.serviceCancelAsync(pass, parent_pkhref, parent_refnum, parent_service_id, null);
        }
        
        /// <remarks/>
        public void serviceCancelAsync(string pass, int parent_pkhref, int parent_refnum, int parent_service_id, object userState) {
            if ((this.serviceCancelOperationCompleted == null)) {
                this.serviceCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviceCancelOperationCompleted);
            }
            this.InvokeAsync("serviceCancel", new object[] {
                        pass,
                        parent_pkhref,
                        parent_refnum,
                        parent_service_id}, this.serviceCancelOperationCompleted, userState);
        }
        
        private void OnserviceCancelOperationCompleted(object arg) {
            if ((this.serviceCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviceCancelCompleted(this, new serviceCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/validate", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public int validate(string pass, string ver_code, int user_key, int service_id) {
            object[] results = this.Invoke("validate", new object[] {
                        pass,
                        ver_code,
                        user_key,
                        service_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void validateAsync(string pass, string ver_code, int user_key, int service_id) {
            this.validateAsync(pass, ver_code, user_key, service_id, null);
        }
        
        /// <remarks/>
        public void validateAsync(string pass, string ver_code, int user_key, int service_id, object userState) {
            if ((this.validateOperationCompleted == null)) {
                this.validateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateOperationCompleted);
            }
            this.InvokeAsync("validate", new object[] {
                        pass,
                        ver_code,
                        user_key,
                        service_id}, this.validateOperationCompleted, userState);
        }
        
        private void OnvalidateOperationCompleted(object arg) {
            if ((this.validateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateCompleted(this, new validateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/validateToken", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public string validateToken(string pass, string token, int user_key, int service_id) {
            object[] results = this.Invoke("validateToken", new object[] {
                        pass,
                        token,
                        user_key,
                        service_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void validateTokenAsync(string pass, string token, int user_key, int service_id) {
            this.validateTokenAsync(pass, token, user_key, service_id, null);
        }
        
        /// <remarks/>
        public void validateTokenAsync(string pass, string token, int user_key, int service_id, object userState) {
            if ((this.validateTokenOperationCompleted == null)) {
                this.validateTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateTokenOperationCompleted);
            }
            this.InvokeAsync("validateToken", new object[] {
                        pass,
                        token,
                        user_key,
                        service_id}, this.validateTokenOperationCompleted, userState);
        }
        
        private void OnvalidateTokenOperationCompleted(object arg) {
            if ((this.validateTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateTokenCompleted(this, new validateTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/servicePay", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("serial")]
        public int servicePay(string pass, string ver_code, int user_key, int service_id, int amount) {
            object[] results = this.Invoke("servicePay", new object[] {
                        pass,
                        ver_code,
                        user_key,
                        service_id,
                        amount});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void servicePayAsync(string pass, string ver_code, int user_key, int service_id, int amount) {
            this.servicePayAsync(pass, ver_code, user_key, service_id, amount, null);
        }
        
        /// <remarks/>
        public void servicePayAsync(string pass, string ver_code, int user_key, int service_id, int amount, object userState) {
            if ((this.servicePayOperationCompleted == null)) {
                this.servicePayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnservicePayOperationCompleted);
            }
            this.InvokeAsync("servicePay", new object[] {
                        pass,
                        ver_code,
                        user_key,
                        service_id,
                        amount}, this.servicePayOperationCompleted, userState);
        }
        
        private void OnservicePayOperationCompleted(object arg) {
            if ((this.servicePayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.servicePayCompleted(this, new servicePayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/info", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("office")]
        public string[] info(string pass, int user_key) {
            object[] results = this.Invoke("info", new object[] {
                        pass,
                        user_key});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void infoAsync(string pass, int user_key) {
            this.infoAsync(pass, user_key, null);
        }
        
        /// <remarks/>
        public void infoAsync(string pass, int user_key, object userState) {
            if ((this.infoOperationCompleted == null)) {
                this.infoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninfoOperationCompleted);
            }
            this.InvokeAsync("info", new object[] {
                        pass,
                        user_key}, this.infoOperationCompleted, userState);
        }
        
        private void OninfoOperationCompleted(object arg) {
            if ((this.infoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.infoCompleted(this, new infoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.epishkhan.ir/nwsv1/index.php/serviceCall", RequestNamespace="http://www.wso2.org/php/xsd", ResponseNamespace="http://www.wso2.org/php/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("serial")]
        public int serviceCall(string pass, string ver_code, int user_key, int service_id) {
            object[] results = this.Invoke("serviceCall", new object[] {
                        pass,
                        ver_code,
                        user_key,
                        service_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void serviceCallAsync(string pass, string ver_code, int user_key, int service_id) {
            this.serviceCallAsync(pass, ver_code, user_key, service_id, null);
        }
        
        /// <remarks/>
        public void serviceCallAsync(string pass, string ver_code, int user_key, int service_id, object userState) {
            if ((this.serviceCallOperationCompleted == null)) {
                this.serviceCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviceCallOperationCompleted);
            }
            this.InvokeAsync("serviceCall", new object[] {
                        pass,
                        ver_code,
                        user_key,
                        service_id}, this.serviceCallOperationCompleted, userState);
        }
        
        private void OnserviceCallOperationCompleted(object arg) {
            if ((this.serviceCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviceCallCompleted(this, new serviceCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void serviceRefundCompletedEventHandler(object sender, serviceRefundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviceRefundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviceRefundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void verifyCompletedEventHandler(object sender, verifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void serviceCancelCompletedEventHandler(object sender, serviceCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviceCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviceCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void validateCompletedEventHandler(object sender, validateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void validateTokenCompletedEventHandler(object sender, validateTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void servicePayCompletedEventHandler(object sender, servicePayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class servicePayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal servicePayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void infoCompletedEventHandler(object sender, infoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class infoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal infoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void serviceCallCompletedEventHandler(object sender, serviceCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviceCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviceCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591