//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    
    public partial class prs_tblSooratHesab_HeaderSelect
    {
        public long fldId { get; set; }
        public string fldTaxId { get; set; }
        public string fldIndatim { get; set; }
        public string fldIndati2m { get; set; }
        public byte fldInty { get; set; }
        public Nullable<byte> fldInp { get; set; }
        public string fldInno { get; set; }
        public string fldIrtaxId { get; set; }
        public Nullable<long> fldKharidarId { get; set; }
        public Nullable<long> fldForooshandeId { get; set; }
        public long fldUserId { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldf_Name { get; set; }
        public string fldkh_name { get; set; }
        public string fldTypeSooratHesab { get; set; }
        public string fldNamePettern { get; set; }
        public byte fldStatus { get; set; }
        public string fldStatusName { get; set; }
        public string fldReferenceNumber { get; set; }
        public string fldUid { get; set; }
        public string fldf_NationalCode { get; set; }
        public string fldkh_fldNationalCode { get; set; }
        public string fldf_CodeEghtesadi { get; set; }
        public string fldkh_CodeEghtesadi { get; set; }
        public string fldSubject { get; set; }
    }
}
