//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Areas.Tax.Models
{
    using System;
    
    public partial class prs_tblTarfGharardadSelect
    {
        public int fldId { get; set; }
        public long fldShakhsId { get; set; }
        public string fldUniqId { get; set; }
        public byte[] fldPrivateKey { get; set; }
        public byte[] fldSignatureCertificate { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNameShakhs { get; set; }
        public string fldCodeEghtesadi { get; set; }
        public string fldCodeShobe { get; set; }
        public string fldNationalCode { get; set; }
        public string fldCodePosti { get; set; }
        public string fldNameTypeShakhs { get; set; }
    }
}
