//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_AmountCostSelect
    {
        public int fldID { get; set; }
        public int fldAmount { get; set; }
        public string fldDateAmount { get; set; }
        public string fldCostName { get; set; }
        public int fldCostID { get; set; }
        public string fldCountryDivisionsName { get; set; }
        public long fldCountryDivisionsID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public Nullable<bool> fldCountryDivisionsTreeApply { get; set; }
        public string fldCarSeriesName { get; set; }
        public Nullable<long> fldCarSeriesID { get; set; }
        public Nullable<bool> fldCarSeriesTreeApply { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryType { get; set; }
        public Nullable<int> CarCode { get; set; }
        public Nullable<int> CarType { get; set; }
        public Nullable<bool> fldEffectiveUser { get; set; }
        public string fldEffectiveUserName { get; set; }
        public Nullable<bool> fldEffectiveOffice { get; set; }
        public string fldEffectiveOfficeName { get; set; }
        public Nullable<bool> fldEffectiveMunicipality { get; set; }
        public string fldEffectiveMunicipalityName { get; set; }
    }
}
