//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_Collection_LogSelect
    {
        public long fldID { get; set; }
        public System.DateTime تاریخ_وصول { get; set; }
        public int مبلغ { get; set; }
        public string کد_فیش { get; set; }
        public string کد_رهگیری { get; set; }
        public string سریال_برچسب { get; set; }
        public string کد_رهگیری_پیشخوان { get; set; }
        public string تاریخ_شروع { get; set; }
        public string تاریخ_پایان { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string نوع_پرداخت { get; set; }
        public string کاربرایجادکننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
