//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_CarPatternModel_LogSelect
    {
        public int fldID { get; set; }
        public Nullable<byte> تعداد_سیلندر { get; set; }
        public Nullable<byte> تعداد_چرخ { get; set; }
        public Nullable<byte> تعداد_محور { get; set; }
        public Nullable<int> حجم_موتور { get; set; }
        public string توضیحات { get; set; }
        public string تاریخ_ایجاد { get; set; }
        public string نام { get; set; }
        public string نوع_سوخت { get; set; }
        public string کاربرایجادکننده { get; set; }
        public string نوع_تغییرات { get; set; }
        public Nullable<System.TimeSpan> ساعت_تغییرات { get; set; }
        public string موقعیت_کاربر_ایجاد_کننده { get; set; }
    }
}
