//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_CarSeriesSelect
    {
        public long fldID { get; set; }
        public string fldCarMakeName { get; set; }
        public Nullable<int> fldCarMakeID { get; set; }
        public string fldCarAccountTypeName { get; set; }
        public Nullable<int> fldCarAccountTypeID { get; set; }
        public string fldCabinTypeName { get; set; }
        public Nullable<int> fldCabinTypeID { get; set; }
        public string fldCarSystemName { get; set; }
        public Nullable<int> fldCarSystemID { get; set; }
        public string fldCarModelName { get; set; }
        public Nullable<int> fldCarModelID { get; set; }
        public string fldCarClassName { get; set; }
        public Nullable<int> fldCarClassID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
    }
}
