//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_CarClassSelect
    {
        public int fldID { get; set; }
        public string fldName { get; set; }
        public string fldCarModelName { get; set; }
        public int fldCarModelID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public int fldCarPatternModelID { get; set; }
        public Nullable<byte> fldCylinderNumber { get; set; }
        public Nullable<byte> fldWheelNumber { get; set; }
        public Nullable<byte> fldPivotNumber { get; set; }
        public Nullable<int> fldContentMotor { get; set; }
        public string fldFuelTypeName { get; set; }
        public Nullable<int> fldFuelTypeID { get; set; }
        public string fldCarPatternModelName { get; set; }
        public string fldNameCarSystem { get; set; }
        public string fldNameCabinType { get; set; }
        public string fldNameCarAccountType { get; set; }
        public string fldNameCarMake { get; set; }
    }
}
