//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_ListeSiyahSelect
    {
        public int fldId { get; set; }
        public long fldCarId { get; set; }
        public byte fldType { get; set; }
        public string fldMsg { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldTypeS { get; set; }
    }
}
