//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_LogInProgramSelect
    {
        public int fldID { get; set; }
        public long fldUserID { get; set; }
        public string fldMacAddress { get; set; }
        public string fldIPAddress { get; set; }
        public string fldDateIN { get; set; }
        public Nullable<System.TimeSpan> TIMEIN { get; set; }
        public string fldUserName { get; set; }
        public string fldPositionUser { get; set; }
    }
}
