//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_PardakhtFiles_DetailSelect
    {
        public int fldId { get; set; }
        public string fldShenaseGhabz { get; set; }
        public string fldShomarePardakht { get; set; }
        public string fldTarikhPardakht { get; set; }
        public string fldCodeRahgiry { get; set; }
        public int fldNahvePardakhtId { get; set; }
        public int fldPardakhtFileId { get; set; }
        public long fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldNahvePardakhtName { get; set; }
        public string fldBankName { get; set; }
        public int fldBankId { get; set; }
        public int fldCountryDivisionId { get; set; }
        public long fldGhabzNumber { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldVIN { get; set; }
    }
}
