//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_RptLogCarFile
    {
        public long fldID { get; set; }
        public long fldCarID { get; set; }
        public Nullable<int> fldBargSabzFileId { get; set; }
        public Nullable<int> fldCartFileId { get; set; }
        public Nullable<int> fldSanadForoshFileId { get; set; }
        public Nullable<int> fldCartBackFileId { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldVIN { get; set; }
        public string fldUserName { get; set; }
        public System.DateTime fldDate { get; set; }
        public string LogType { get; set; }
        public string fldPlaqueNumber { get; set; }
        public string fldNameOwner { get; set; }
    }
}
