//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_RegisterDetailselect
    {
        public int fldid { get; set; }
        public Nullable<long> fldRegisterId { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldCodeMelli { get; set; }
        public string fldFather { get; set; }
        public string fldBdate { get; set; }
    }
}
