//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_SingleCarfileSelect
    {
        public long fldID { get; set; }
        public long fldCarID { get; set; }
        public int fldCarPlaqueID { get; set; }
        public Nullable<System.DateTime> fldDatePlaque { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public Nullable<int> fldBargSabzFileId { get; set; }
        public Nullable<int> fldCartFileId { get; set; }
        public Nullable<int> fldSanadForoshFileId { get; set; }
        public Nullable<int> fldCartBackFileId { get; set; }
        public bool fldAccept { get; set; }
        public Nullable<long> fldAcceptUser { get; set; }
        public Nullable<System.DateTime> fldAcceptDate { get; set; }
        public Nullable<bool> fldTypeEntezami { get; set; }
    }
}
