//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_CarFile_LogSelect2
    {
        public long fldID { get; set; }
        public long fldLogID { get; set; }
        public string fldDatePlaque { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldCarPlaqueName { get; set; }
        public string fldUserID { get; set; }
        public string fldTypeLogName { get; set; }
        public Nullable<System.TimeSpan> fldTime { get; set; }
        public string fldUserLocation { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldVIN { get; set; }
        public Nullable<short> fldModel { get; set; }
        public Nullable<System.DateTime> fldStartDateInsurance { get; set; }
        public string fldColor { get; set; }
        public string fldCarAccountTypeName { get; set; }
        public string fldCabinTypeName { get; set; }
        public string fldCarClassName { get; set; }
        public string fldCarSystemName { get; set; }
        public string fldCarModelName { get; set; }
        public string fldTypePlaque { get; set; }
        public string fldCarMakeName { get; set; }
    }
}
