//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_DiscountSelect
    {
        public int fldID { get; set; }
        public string fldName { get; set; }
        public string fldStartDate { get; set; }
        public string fldEndDate { get; set; }
        public string fldComplicationPrice { get; set; }
        public string fldFinePrice { get; set; }
        public string fldValueAddedPrice { get; set; }
        public string fldOtherPrice { get; set; }
        public int fldPercentDiscount { get; set; }
        public string fldCountryDivisionName { get; set; }
        public long fldCountryDivisionID { get; set; }
        public string fldCarSeriesName { get; set; }
        public long fldCarSeriesID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldDateOf { get; set; }
        public string fldEffectiveUserName { get; set; }
        public string fldEffectiveOfficeName { get; set; }
        public string fldEffectiveMunicipalityName { get; set; }
        public Nullable<bool> fldEffectiveUser { get; set; }
        public Nullable<bool> fldEffectiveOffice { get; set; }
        public Nullable<bool> fldEffectiveMunicipality { get; set; }
        public bool fldOtherPriceID { get; set; }
        public bool fldValueAddedPriceID { get; set; }
        public bool fldFinePriceID { get; set; }
        public bool fldComplicationPriceID { get; set; }
        public string fldCarSeriesID_S { get; set; }
    }
}
