//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_GuestUserSelect
    {
        public int fldId { get; set; }
        public string fldMobile { get; set; }
        public string fldNationalCode { get; set; }
        public string fldAcceptCode { get; set; }
        public string fldPassword { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldDesc { get; set; }
        public Nullable<bool> fldFlag { get; set; }
        public bool fldType { get; set; }
        public int fldMunId { get; set; }
        public int fldStateId { get; set; }
        public string fldNameState { get; set; }
        public string fldMunName { get; set; }
        public string fldTarikhTavalod { get; set; }
        public string fldName { get; set; }
        public string fldFatherName { get; set; }
        public string fldSerialShenasname { get; set; }
        public string fldSh_Shenasname { get; set; }
        public string fldMahalSodoor { get; set; }
    }
}
