//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_KolParvandeHaByUserId
    {
        public Nullable<long> fldID { get; set; }
        public Nullable<long> fldCarID { get; set; }
        public Nullable<int> fldCarPlaqueID { get; set; }
        public Nullable<System.DateTime> fldDatePlaque { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldMobile { get; set; }
        public string fldVIN { get; set; }
        public string fldName { get; set; }
        public string fldMelli_EconomicCode { get; set; }
        public string carModel { get; set; }
        public string CarClass { get; set; }
        public Nullable<short> fldModel { get; set; }
        public string haveArchive { get; set; }
        public string fldUserName { get; set; }
        public Nullable<bool> fldAccept { get; set; }
        public Nullable<byte> fldAcceptCollection { get; set; }
        public Nullable<byte> fldAcceptCarExperience { get; set; }
        public string fldAcceptName { get; set; }
        public string fldAcceptCollectionName { get; set; }
        public string fldAcceptCarExperienceName { get; set; }
    }
}
