//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class Sp_tblPishkhanResiptSelect
    {
        public int fldId { get; set; }
        public Nullable<long> fldCarFileId { get; set; }
        public string flddate { get; set; }
        public Nullable<int> fldPrice { get; set; }
        public Nullable<int> fldMaliat { get; set; }
        public string fldDesc { get; set; }
        public Nullable<long> fldUserId { get; set; }
        public string fldName { get; set; }
        public string fldMelli_EconomicCode { get; set; }
        public string fldUserName { get; set; }
        public string fldVIN { get; set; }
        public Nullable<byte> fldStatus { get; set; }
        public string fldSerial { get; set; }
        public string fldPosString { get; set; }
        public string fldTermId { get; set; }
        public string fldTrace { get; set; }
        public string fldRRN { get; set; }
        public string fldPishkhanRahgiri { get; set; }
        public Nullable<System.TimeSpan> fldTime { get; set; }
    }
}
