//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_VariziHa
    {
        public long fldID { get; set; }
        public long fldCarFileID { get; set; }
        public string Tarikh { get; set; }
        public string fldMelli_EconomicCode { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldMotorNumber { get; set; }
        public long fldCarId { get; set; }
        public string fldName { get; set; }
        public int fldShowMoney { get; set; }
    }
}
