//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class rpt_CollectionSelect
    {
        public long fldID { get; set; }
        public long fldCarFileID { get; set; }
        public string fldCollectionDate { get; set; }
        public int fldPrice { get; set; }
        public int fldSettleTypeID { get; set; }
        public Nullable<long> fldPeacockeryCode { get; set; }
        public Nullable<long> fldTrackCode { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldSettleTypeName { get; set; }
        public byte fldSettleTypeCode { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldVIN { get; set; }
        public short fldModel { get; set; }
        public string fldStartDateInsurance { get; set; }
        public string fldColor { get; set; }
        public string fldCarModelName { get; set; }
        public string fldCarClassName { get; set; }
        public string fldPlaqueNumber { get; set; }
        public string fldSerial { get; set; }
        public string fldPlaqueTypeName { get; set; }
        public string fldPlaqueCityName { get; set; }
        public string fldDatePlaque { get; set; }
        public long fldCountryDivisionsID { get; set; }
        public Nullable<int> fldCountryDivisionsCode { get; set; }
        public Nullable<int> fldCountryDivisionsType { get; set; }
        public string fldCountryDivisionsName { get; set; }
        public long fldOwnerID { get; set; }
        public string fldOwnerName { get; set; }
        public string fldCarSystemName { get; set; }
        public int fldCarSystemID { get; set; }
    }
}
