//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_ContactSelect
    {
        public int fldID { get; set; }
        public string fldName { get; set; }
        public string fldFamily { get; set; }
        public string fldTel1 { get; set; }
        public string fldTel2 { get; set; }
        public string fldMobile1 { get; set; }
        public string fldMobile2 { get; set; }
        public string fldEmail { get; set; }
        public string fldFax { get; set; }
        public string fldWebsite { get; set; }
        public string fldPostalCode { get; set; }
        public int fldAccostTypeID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldAccostName { get; set; }
    }
}
