//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_CachedSearchCarFileSelect
    {
        public int fldCode { get; set; }
        public int fldID { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldVIN { get; set; }
        public short fldModel { get; set; }
        public string fldCarModelName { get; set; }
        public string fldCarClassName { get; set; }
        public long fldCarFileId { get; set; }
        public long fldUserId { get; set; }
        public string fldDesc { get; set; }
        public System.DateTime fldDate { get; set; }
        public string fldName { get; set; }
        public string fldMelli_EconomicCode { get; set; }
        public string fldPlaqueNumber { get; set; }
        public string fldCarAccountName { get; set; }
        public string fldCarsystemName { get; set; }
        public string fldColor { get; set; }
        public string fldFuleTypeName { get; set; }
        public Nullable<byte> fldAccept { get; set; }
        public string fldAcceptName { get; set; }
        public Nullable<byte> fldIsBalckList { get; set; }
        public Nullable<int> fldAccountTypeId { get; set; }
    }
}
