//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_MonthlyCollectionTipChart
    {
        public Nullable<int> fldPrice { get; set; }
        public Nullable<int> tedad { get; set; }
        public string fldName { get; set; }
        public string fldMonth { get; set; }
        public string fldMonthName { get; set; }
    }
}
