//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_MainSettingSelect
    {
        public int fldID { get; set; }
        public bool fldLateFine { get; set; }
        public bool fldTax { get; set; }
        public string fldCountryDivisionsName { get; set; }
        public long fldCountryDivisionsID { get; set; }
        public long fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public string fldImplementationDate { get; set; }
        public string fldCountryDivisionsTreeApply { get; set; }
        public string fldCarSeriesName { get; set; }
        public Nullable<long> fldCarSeriesID { get; set; }
        public string fldCarSeriesTreeApply { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> CountryType { get; set; }
        public Nullable<int> CarCode { get; set; }
        public Nullable<int> CarType { get; set; }
        public Nullable<bool> fldFineType { get; set; }
        public string fldFineTypeName { get; set; }
        public Nullable<bool> fldFirstInsurance { get; set; }
        public string fldFirstInsurance1 { get; set; }
        public Nullable<bool> fldCountryDivisionsTreeApplyId { get; set; }
        public Nullable<bool> fldCarSeriesTreeApplyId { get; set; }
    }
}
