//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class sp_Report_CountryDivitionSelect
    {
        public int fldID { get; set; }
        public Nullable<long> fldCountryDivisionsID { get; set; }
        public string fldCountryDivisionsName { get; set; }
        public Nullable<int> fldReportsID { get; set; }
        public Nullable<long> fldUserID { get; set; }
        public string fldDesc { get; set; }
        public string fldDate { get; set; }
        public string fldUserName { get; set; }
        public byte[] fldReport { get; set; }
        public int fldReportTypeId { get; set; }
        public string fldReportTypeName { get; set; }
    }
}
