//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avarez.Models
{
    using System;
    
    public partial class Sp_tblOfficeReciptSelect
    {
        public System.Guid fldId { get; set; }
        public string fldTarikh { get; set; }
        public Nullable<int> fldShomare { get; set; }
        public Nullable<short> fldYear { get; set; }
        public Nullable<int> fldUserId { get; set; }
        public Nullable<long> fldCarId { get; set; }
        public Nullable<int> fldPrice { get; set; }
        public string fldMotorNumber { get; set; }
        public string fldShasiNumber { get; set; }
        public string fldVIN { get; set; }
        public string fldPlaqueCityName { get; set; }
        public string fldOwnerName { get; set; }
        public string fldPlaqueNumber { get; set; }
        public string fldSerial { get; set; }
        public string fldMelli_EconomicCode { get; set; }
        public Nullable<int> fldmaliat { get; set; }
    }
}
